package com.bornfire.brf.entities;

import java.math.BigDecimal;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "CBUAE_BRF5_5_SUMMARYTABLE7")

public class CBUAE_BRF5_5_Summary_Entity7 {
	
	private String	r0820_resident_item;
	private BigDecimal	r0820_resident_government_private_sector_outstanding_balance;
	private BigDecimal	r0820_resident_government_private_sector_loans_stage3;
	private BigDecimal	r0820_resident_government_private_sector_stage3_provisions;
	private BigDecimal	r0820_resident_government_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_gre_outstanding_balance;
	private BigDecimal	r0820_resident_gre_loans_stage3;
	private BigDecimal	r0820_resident_gre_stage3_provisions;
	private BigDecimal	r0820_resident_gre_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_private_sector_outstanding_balance;
	private BigDecimal	r0820_resident_private_sector_loans_stage3;
	private BigDecimal	r0820_resident_private_sector_stage3_provisions;
	private BigDecimal	r0820_resident_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_sme_outstanding_balance;
	private BigDecimal	r0820_resident_sme_loans_stage3;
	private BigDecimal	r0820_resident_sme_stage3_provisions;
	private BigDecimal	r0820_resident_sme_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_hni_outstanding_balance;
	private BigDecimal	r0820_resident_hni_loans_stage3;
	private BigDecimal	r0820_resident_hni_stage3_provisions;
	private BigDecimal	r0820_resident_hni_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_individuals_outstanding_balance;
	private BigDecimal	r0820_resident_individuals_loans_stage3;
	private BigDecimal	r0820_resident_individuals_stage3_provisions;
	private BigDecimal	r0820_resident_individuals_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_nonbanking_financial_outstanding_balance;
	private BigDecimal	r0820_resident_nonbanking_financial_loans_stage3;
	private BigDecimal	r0820_resident_nonbanking_financial_stage3_provisions;
	private BigDecimal	r0820_resident_nonbanking_financial_provision_interest_legacy_interest;
	private BigDecimal	r0820_resident_tradebills_outstanding_balance;
	private BigDecimal	r0820_resident_tradebills_loans_stage3;
	private BigDecimal	r0820_resident_tradebills_stage3_provisions;
	private BigDecimal	r0820_resident_tradebills_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_government_private_sector_outstanding_balance;
	private BigDecimal	r0820_non_resident_government_private_sector_loans_stage3;
	private BigDecimal	r0820_non_resident_government_private_sector_stage3_provisions;
	private BigDecimal	r0820_non_resident_government_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_gre_outstanding_balance;
	private BigDecimal	r0820_non_resident_gre_loans_stage3;
	private BigDecimal	r0820_non_resident_gre_stage3_provisions;
	private BigDecimal	r0820_non_resident_gre_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_private_sector_outstanding_balance;
	private BigDecimal	r0820_non_resident_private_sector_loans_stage3;
	private BigDecimal	r0820_non_resident_private_sector_stage3_provisions;
	private BigDecimal	r0820_non_resident_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_sme_outstanding_balance;
	private BigDecimal	r0820_non_resident_sme_loans_stage3;
	private BigDecimal	r0820_non_resident_sme_stage3_provisions;
	private BigDecimal	r0820_non_resident_sme_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_hni_outstanding_balance;
	private BigDecimal	r0820_non_resident_hni_loans_stage3;
	private BigDecimal	r0820_non_resident_hni_stage3_provisions;
	private BigDecimal	r0820_non_resident_hni_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_individuals_outstanding_balance;
	private BigDecimal	r0820_non_resident_individuals_loans_stage3;
	private BigDecimal	r0820_non_resident_individuals_stage3_provisions;
	private BigDecimal	r0820_non_resident_individuals_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_nonbanking_financial_outstanding_balance;
	private BigDecimal	r0820_non_resident_nonbanking_financial_loans_stage3;
	private BigDecimal	r0820_non_resident_nonbanking_financial_stage3_provisions;
	private BigDecimal	r0820_non_resident_nonbanking_financial_provision_interest_legacy_interest;
	private BigDecimal	r0820_non_resident_tradebills_outstanding_balance;
	private BigDecimal	r0820_non_resident_tradebills_loans_stage3;
	private BigDecimal	r0820_non_resident_tradebills_stage3_provisions;
	private BigDecimal	r0820_non_resident_tradebills_provision_interest_legacy_interest;
	private String	r0830_resident_item;
	private BigDecimal	r0830_resident_government_private_sector_outstanding_balance;
	private BigDecimal	r0830_resident_government_private_sector_loans_stage3;
	private BigDecimal	r0830_resident_government_private_sector_stage3_provisions;
	private BigDecimal	r0830_resident_government_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_gre_outstanding_balance;
	private BigDecimal	r0830_resident_gre_loans_stage3;
	private BigDecimal	r0830_resident_gre_stage3_provisions;
	private BigDecimal	r0830_resident_gre_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_private_sector_outstanding_balance;
	private BigDecimal	r0830_resident_private_sector_loans_stage3;
	private BigDecimal	r0830_resident_private_sector_stage3_provisions;
	private BigDecimal	r0830_resident_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_sme_outstanding_balance;
	private BigDecimal	r0830_resident_sme_loans_stage3;
	private BigDecimal	r0830_resident_sme_stage3_provisions;
	private BigDecimal	r0830_resident_sme_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_hni_outstanding_balance;
	private BigDecimal	r0830_resident_hni_loans_stage3;
	private BigDecimal	r0830_resident_hni_stage3_provisions;
	private BigDecimal	r0830_resident_hni_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_individuals_outstanding_balance;
	private BigDecimal	r0830_resident_individuals_loans_stage3;
	private BigDecimal	r0830_resident_individuals_stage3_provisions;
	private BigDecimal	r0830_resident_individuals_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_nonbanking_financial_outstanding_balance;
	private BigDecimal	r0830_resident_nonbanking_financial_loans_stage3;
	private BigDecimal	r0830_resident_nonbanking_financial_stage3_provisions;
	private BigDecimal	r0830_resident_nonbanking_financial_provision_interest_legacy_interest;
	private BigDecimal	r0830_resident_tradebills_outstanding_balance;
	private BigDecimal	r0830_resident_tradebills_loans_stage3;
	private BigDecimal	r0830_resident_tradebills_stage3_provisions;
	private BigDecimal	r0830_resident_tradebills_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_government_private_sector_outstanding_balance;
	private BigDecimal	r0830_non_resident_government_private_sector_loans_stage3;
	private BigDecimal	r0830_non_resident_government_private_sector_stage3_provisions;
	private BigDecimal	r0830_non_resident_government_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_gre_outstanding_balance;
	private BigDecimal	r0830_non_resident_gre_loans_stage3;
	private BigDecimal	r0830_non_resident_gre_stage3_provisions;
	private BigDecimal	r0830_non_resident_gre_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_private_sector_outstanding_balance;
	private BigDecimal	r0830_non_resident_private_sector_loans_stage3;
	private BigDecimal	r0830_non_resident_private_sector_stage3_provisions;
	private BigDecimal	r0830_non_resident_private_sector_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_sme_outstanding_balance;
	private BigDecimal	r0830_non_resident_sme_loans_stage3;
	private BigDecimal	r0830_non_resident_sme_stage3_provisions;
	private BigDecimal	r0830_non_resident_sme_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_hni_outstanding_balance;
	private BigDecimal	r0830_non_resident_hni_loans_stage3;
	private BigDecimal	r0830_non_resident_hni_stage3_provisions;
	private BigDecimal	r0830_non_resident_hni_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_individuals_outstanding_balance;
	private BigDecimal	r0830_non_resident_individuals_loans_stage3;
	private BigDecimal	r0830_non_resident_individuals_stage3_provisions;
	private BigDecimal	r0830_non_resident_individuals_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_nonbanking_financial_outstanding_balance;
	private BigDecimal	r0830_non_resident_nonbanking_financial_loans_stage3;
	private BigDecimal	r0830_non_resident_nonbanking_financial_stage3_provisions;
	private BigDecimal	r0830_non_resident_nonbanking_financial_provision_interest_legacy_interest;
	private BigDecimal	r0830_non_resident_tradebills_outstanding_balance;
	private BigDecimal	r0830_non_resident_tradebills_loans_stage3;
	private BigDecimal	r0830_non_resident_tradebills_stage3_provisions;
	private BigDecimal	r0830_non_resident_tradebills_provision_interest_legacy_interest;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	report_date;
	private String	report_version;
	private String	report_frequency;
	private String	report_code;
	private String	report_desc;
	private String	entity_flg;
	private String	modify_flg;
	private String	del_flg;
	public String getR0820_resident_item() {
		return r0820_resident_item;
	}
	public void setR0820_resident_item(String r0820_resident_item) {
		this.r0820_resident_item = r0820_resident_item;
	}
	public BigDecimal getR0820_resident_government_private_sector_outstanding_balance() {
		return r0820_resident_government_private_sector_outstanding_balance;
	}
	public void setR0820_resident_government_private_sector_outstanding_balance(
			BigDecimal r0820_resident_government_private_sector_outstanding_balance) {
		this.r0820_resident_government_private_sector_outstanding_balance = r0820_resident_government_private_sector_outstanding_balance;
	}
	public BigDecimal getR0820_resident_government_private_sector_loans_stage3() {
		return r0820_resident_government_private_sector_loans_stage3;
	}
	public void setR0820_resident_government_private_sector_loans_stage3(
			BigDecimal r0820_resident_government_private_sector_loans_stage3) {
		this.r0820_resident_government_private_sector_loans_stage3 = r0820_resident_government_private_sector_loans_stage3;
	}
	public BigDecimal getR0820_resident_government_private_sector_stage3_provisions() {
		return r0820_resident_government_private_sector_stage3_provisions;
	}
	public void setR0820_resident_government_private_sector_stage3_provisions(
			BigDecimal r0820_resident_government_private_sector_stage3_provisions) {
		this.r0820_resident_government_private_sector_stage3_provisions = r0820_resident_government_private_sector_stage3_provisions;
	}
	public BigDecimal getR0820_resident_government_private_sector_provision_interest_legacy_interest() {
		return r0820_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public void setR0820_resident_government_private_sector_provision_interest_legacy_interest(
			BigDecimal r0820_resident_government_private_sector_provision_interest_legacy_interest) {
		this.r0820_resident_government_private_sector_provision_interest_legacy_interest = r0820_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_gre_outstanding_balance() {
		return r0820_resident_gre_outstanding_balance;
	}
	public void setR0820_resident_gre_outstanding_balance(BigDecimal r0820_resident_gre_outstanding_balance) {
		this.r0820_resident_gre_outstanding_balance = r0820_resident_gre_outstanding_balance;
	}
	public BigDecimal getR0820_resident_gre_loans_stage3() {
		return r0820_resident_gre_loans_stage3;
	}
	public void setR0820_resident_gre_loans_stage3(BigDecimal r0820_resident_gre_loans_stage3) {
		this.r0820_resident_gre_loans_stage3 = r0820_resident_gre_loans_stage3;
	}
	public BigDecimal getR0820_resident_gre_stage3_provisions() {
		return r0820_resident_gre_stage3_provisions;
	}
	public void setR0820_resident_gre_stage3_provisions(BigDecimal r0820_resident_gre_stage3_provisions) {
		this.r0820_resident_gre_stage3_provisions = r0820_resident_gre_stage3_provisions;
	}
	public BigDecimal getR0820_resident_gre_provision_interest_legacy_interest() {
		return r0820_resident_gre_provision_interest_legacy_interest;
	}
	public void setR0820_resident_gre_provision_interest_legacy_interest(
			BigDecimal r0820_resident_gre_provision_interest_legacy_interest) {
		this.r0820_resident_gre_provision_interest_legacy_interest = r0820_resident_gre_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_private_sector_outstanding_balance() {
		return r0820_resident_private_sector_outstanding_balance;
	}
	public void setR0820_resident_private_sector_outstanding_balance(
			BigDecimal r0820_resident_private_sector_outstanding_balance) {
		this.r0820_resident_private_sector_outstanding_balance = r0820_resident_private_sector_outstanding_balance;
	}
	public BigDecimal getR0820_resident_private_sector_loans_stage3() {
		return r0820_resident_private_sector_loans_stage3;
	}
	public void setR0820_resident_private_sector_loans_stage3(BigDecimal r0820_resident_private_sector_loans_stage3) {
		this.r0820_resident_private_sector_loans_stage3 = r0820_resident_private_sector_loans_stage3;
	}
	public BigDecimal getR0820_resident_private_sector_stage3_provisions() {
		return r0820_resident_private_sector_stage3_provisions;
	}
	public void setR0820_resident_private_sector_stage3_provisions(
			BigDecimal r0820_resident_private_sector_stage3_provisions) {
		this.r0820_resident_private_sector_stage3_provisions = r0820_resident_private_sector_stage3_provisions;
	}
	public BigDecimal getR0820_resident_private_sector_provision_interest_legacy_interest() {
		return r0820_resident_private_sector_provision_interest_legacy_interest;
	}
	public void setR0820_resident_private_sector_provision_interest_legacy_interest(
			BigDecimal r0820_resident_private_sector_provision_interest_legacy_interest) {
		this.r0820_resident_private_sector_provision_interest_legacy_interest = r0820_resident_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_sme_outstanding_balance() {
		return r0820_resident_sme_outstanding_balance;
	}
	public void setR0820_resident_sme_outstanding_balance(BigDecimal r0820_resident_sme_outstanding_balance) {
		this.r0820_resident_sme_outstanding_balance = r0820_resident_sme_outstanding_balance;
	}
	public BigDecimal getR0820_resident_sme_loans_stage3() {
		return r0820_resident_sme_loans_stage3;
	}
	public void setR0820_resident_sme_loans_stage3(BigDecimal r0820_resident_sme_loans_stage3) {
		this.r0820_resident_sme_loans_stage3 = r0820_resident_sme_loans_stage3;
	}
	public BigDecimal getR0820_resident_sme_stage3_provisions() {
		return r0820_resident_sme_stage3_provisions;
	}
	public void setR0820_resident_sme_stage3_provisions(BigDecimal r0820_resident_sme_stage3_provisions) {
		this.r0820_resident_sme_stage3_provisions = r0820_resident_sme_stage3_provisions;
	}
	public BigDecimal getR0820_resident_sme_provision_interest_legacy_interest() {
		return r0820_resident_sme_provision_interest_legacy_interest;
	}
	public void setR0820_resident_sme_provision_interest_legacy_interest(
			BigDecimal r0820_resident_sme_provision_interest_legacy_interest) {
		this.r0820_resident_sme_provision_interest_legacy_interest = r0820_resident_sme_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_hni_outstanding_balance() {
		return r0820_resident_hni_outstanding_balance;
	}
	public void setR0820_resident_hni_outstanding_balance(BigDecimal r0820_resident_hni_outstanding_balance) {
		this.r0820_resident_hni_outstanding_balance = r0820_resident_hni_outstanding_balance;
	}
	public BigDecimal getR0820_resident_hni_loans_stage3() {
		return r0820_resident_hni_loans_stage3;
	}
	public void setR0820_resident_hni_loans_stage3(BigDecimal r0820_resident_hni_loans_stage3) {
		this.r0820_resident_hni_loans_stage3 = r0820_resident_hni_loans_stage3;
	}
	public BigDecimal getR0820_resident_hni_stage3_provisions() {
		return r0820_resident_hni_stage3_provisions;
	}
	public void setR0820_resident_hni_stage3_provisions(BigDecimal r0820_resident_hni_stage3_provisions) {
		this.r0820_resident_hni_stage3_provisions = r0820_resident_hni_stage3_provisions;
	}
	public BigDecimal getR0820_resident_hni_provision_interest_legacy_interest() {
		return r0820_resident_hni_provision_interest_legacy_interest;
	}
	public void setR0820_resident_hni_provision_interest_legacy_interest(
			BigDecimal r0820_resident_hni_provision_interest_legacy_interest) {
		this.r0820_resident_hni_provision_interest_legacy_interest = r0820_resident_hni_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_individuals_outstanding_balance() {
		return r0820_resident_individuals_outstanding_balance;
	}
	public void setR0820_resident_individuals_outstanding_balance(
			BigDecimal r0820_resident_individuals_outstanding_balance) {
		this.r0820_resident_individuals_outstanding_balance = r0820_resident_individuals_outstanding_balance;
	}
	public BigDecimal getR0820_resident_individuals_loans_stage3() {
		return r0820_resident_individuals_loans_stage3;
	}
	public void setR0820_resident_individuals_loans_stage3(BigDecimal r0820_resident_individuals_loans_stage3) {
		this.r0820_resident_individuals_loans_stage3 = r0820_resident_individuals_loans_stage3;
	}
	public BigDecimal getR0820_resident_individuals_stage3_provisions() {
		return r0820_resident_individuals_stage3_provisions;
	}
	public void setR0820_resident_individuals_stage3_provisions(BigDecimal r0820_resident_individuals_stage3_provisions) {
		this.r0820_resident_individuals_stage3_provisions = r0820_resident_individuals_stage3_provisions;
	}
	public BigDecimal getR0820_resident_individuals_provision_interest_legacy_interest() {
		return r0820_resident_individuals_provision_interest_legacy_interest;
	}
	public void setR0820_resident_individuals_provision_interest_legacy_interest(
			BigDecimal r0820_resident_individuals_provision_interest_legacy_interest) {
		this.r0820_resident_individuals_provision_interest_legacy_interest = r0820_resident_individuals_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_nonbanking_financial_outstanding_balance() {
		return r0820_resident_nonbanking_financial_outstanding_balance;
	}
	public void setR0820_resident_nonbanking_financial_outstanding_balance(
			BigDecimal r0820_resident_nonbanking_financial_outstanding_balance) {
		this.r0820_resident_nonbanking_financial_outstanding_balance = r0820_resident_nonbanking_financial_outstanding_balance;
	}
	public BigDecimal getR0820_resident_nonbanking_financial_loans_stage3() {
		return r0820_resident_nonbanking_financial_loans_stage3;
	}
	public void setR0820_resident_nonbanking_financial_loans_stage3(
			BigDecimal r0820_resident_nonbanking_financial_loans_stage3) {
		this.r0820_resident_nonbanking_financial_loans_stage3 = r0820_resident_nonbanking_financial_loans_stage3;
	}
	public BigDecimal getR0820_resident_nonbanking_financial_stage3_provisions() {
		return r0820_resident_nonbanking_financial_stage3_provisions;
	}
	public void setR0820_resident_nonbanking_financial_stage3_provisions(
			BigDecimal r0820_resident_nonbanking_financial_stage3_provisions) {
		this.r0820_resident_nonbanking_financial_stage3_provisions = r0820_resident_nonbanking_financial_stage3_provisions;
	}
	public BigDecimal getR0820_resident_nonbanking_financial_provision_interest_legacy_interest() {
		return r0820_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public void setR0820_resident_nonbanking_financial_provision_interest_legacy_interest(
			BigDecimal r0820_resident_nonbanking_financial_provision_interest_legacy_interest) {
		this.r0820_resident_nonbanking_financial_provision_interest_legacy_interest = r0820_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_resident_tradebills_outstanding_balance() {
		return r0820_resident_tradebills_outstanding_balance;
	}
	public void setR0820_resident_tradebills_outstanding_balance(BigDecimal r0820_resident_tradebills_outstanding_balance) {
		this.r0820_resident_tradebills_outstanding_balance = r0820_resident_tradebills_outstanding_balance;
	}
	public BigDecimal getR0820_resident_tradebills_loans_stage3() {
		return r0820_resident_tradebills_loans_stage3;
	}
	public void setR0820_resident_tradebills_loans_stage3(BigDecimal r0820_resident_tradebills_loans_stage3) {
		this.r0820_resident_tradebills_loans_stage3 = r0820_resident_tradebills_loans_stage3;
	}
	public BigDecimal getR0820_resident_tradebills_stage3_provisions() {
		return r0820_resident_tradebills_stage3_provisions;
	}
	public void setR0820_resident_tradebills_stage3_provisions(BigDecimal r0820_resident_tradebills_stage3_provisions) {
		this.r0820_resident_tradebills_stage3_provisions = r0820_resident_tradebills_stage3_provisions;
	}
	public BigDecimal getR0820_resident_tradebills_provision_interest_legacy_interest() {
		return r0820_resident_tradebills_provision_interest_legacy_interest;
	}
	public void setR0820_resident_tradebills_provision_interest_legacy_interest(
			BigDecimal r0820_resident_tradebills_provision_interest_legacy_interest) {
		this.r0820_resident_tradebills_provision_interest_legacy_interest = r0820_resident_tradebills_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_government_private_sector_outstanding_balance() {
		return r0820_non_resident_government_private_sector_outstanding_balance;
	}
	public void setR0820_non_resident_government_private_sector_outstanding_balance(
			BigDecimal r0820_non_resident_government_private_sector_outstanding_balance) {
		this.r0820_non_resident_government_private_sector_outstanding_balance = r0820_non_resident_government_private_sector_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_government_private_sector_loans_stage3() {
		return r0820_non_resident_government_private_sector_loans_stage3;
	}
	public void setR0820_non_resident_government_private_sector_loans_stage3(
			BigDecimal r0820_non_resident_government_private_sector_loans_stage3) {
		this.r0820_non_resident_government_private_sector_loans_stage3 = r0820_non_resident_government_private_sector_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_government_private_sector_stage3_provisions() {
		return r0820_non_resident_government_private_sector_stage3_provisions;
	}
	public void setR0820_non_resident_government_private_sector_stage3_provisions(
			BigDecimal r0820_non_resident_government_private_sector_stage3_provisions) {
		this.r0820_non_resident_government_private_sector_stage3_provisions = r0820_non_resident_government_private_sector_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_government_private_sector_provision_interest_legacy_interest() {
		return r0820_non_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_government_private_sector_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_government_private_sector_provision_interest_legacy_interest) {
		this.r0820_non_resident_government_private_sector_provision_interest_legacy_interest = r0820_non_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_gre_outstanding_balance() {
		return r0820_non_resident_gre_outstanding_balance;
	}
	public void setR0820_non_resident_gre_outstanding_balance(BigDecimal r0820_non_resident_gre_outstanding_balance) {
		this.r0820_non_resident_gre_outstanding_balance = r0820_non_resident_gre_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_gre_loans_stage3() {
		return r0820_non_resident_gre_loans_stage3;
	}
	public void setR0820_non_resident_gre_loans_stage3(BigDecimal r0820_non_resident_gre_loans_stage3) {
		this.r0820_non_resident_gre_loans_stage3 = r0820_non_resident_gre_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_gre_stage3_provisions() {
		return r0820_non_resident_gre_stage3_provisions;
	}
	public void setR0820_non_resident_gre_stage3_provisions(BigDecimal r0820_non_resident_gre_stage3_provisions) {
		this.r0820_non_resident_gre_stage3_provisions = r0820_non_resident_gre_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_gre_provision_interest_legacy_interest() {
		return r0820_non_resident_gre_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_gre_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_gre_provision_interest_legacy_interest) {
		this.r0820_non_resident_gre_provision_interest_legacy_interest = r0820_non_resident_gre_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_private_sector_outstanding_balance() {
		return r0820_non_resident_private_sector_outstanding_balance;
	}
	public void setR0820_non_resident_private_sector_outstanding_balance(
			BigDecimal r0820_non_resident_private_sector_outstanding_balance) {
		this.r0820_non_resident_private_sector_outstanding_balance = r0820_non_resident_private_sector_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_private_sector_loans_stage3() {
		return r0820_non_resident_private_sector_loans_stage3;
	}
	public void setR0820_non_resident_private_sector_loans_stage3(
			BigDecimal r0820_non_resident_private_sector_loans_stage3) {
		this.r0820_non_resident_private_sector_loans_stage3 = r0820_non_resident_private_sector_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_private_sector_stage3_provisions() {
		return r0820_non_resident_private_sector_stage3_provisions;
	}
	public void setR0820_non_resident_private_sector_stage3_provisions(
			BigDecimal r0820_non_resident_private_sector_stage3_provisions) {
		this.r0820_non_resident_private_sector_stage3_provisions = r0820_non_resident_private_sector_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_private_sector_provision_interest_legacy_interest() {
		return r0820_non_resident_private_sector_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_private_sector_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_private_sector_provision_interest_legacy_interest) {
		this.r0820_non_resident_private_sector_provision_interest_legacy_interest = r0820_non_resident_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_sme_outstanding_balance() {
		return r0820_non_resident_sme_outstanding_balance;
	}
	public void setR0820_non_resident_sme_outstanding_balance(BigDecimal r0820_non_resident_sme_outstanding_balance) {
		this.r0820_non_resident_sme_outstanding_balance = r0820_non_resident_sme_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_sme_loans_stage3() {
		return r0820_non_resident_sme_loans_stage3;
	}
	public void setR0820_non_resident_sme_loans_stage3(BigDecimal r0820_non_resident_sme_loans_stage3) {
		this.r0820_non_resident_sme_loans_stage3 = r0820_non_resident_sme_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_sme_stage3_provisions() {
		return r0820_non_resident_sme_stage3_provisions;
	}
	public void setR0820_non_resident_sme_stage3_provisions(BigDecimal r0820_non_resident_sme_stage3_provisions) {
		this.r0820_non_resident_sme_stage3_provisions = r0820_non_resident_sme_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_sme_provision_interest_legacy_interest() {
		return r0820_non_resident_sme_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_sme_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_sme_provision_interest_legacy_interest) {
		this.r0820_non_resident_sme_provision_interest_legacy_interest = r0820_non_resident_sme_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_hni_outstanding_balance() {
		return r0820_non_resident_hni_outstanding_balance;
	}
	public void setR0820_non_resident_hni_outstanding_balance(BigDecimal r0820_non_resident_hni_outstanding_balance) {
		this.r0820_non_resident_hni_outstanding_balance = r0820_non_resident_hni_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_hni_loans_stage3() {
		return r0820_non_resident_hni_loans_stage3;
	}
	public void setR0820_non_resident_hni_loans_stage3(BigDecimal r0820_non_resident_hni_loans_stage3) {
		this.r0820_non_resident_hni_loans_stage3 = r0820_non_resident_hni_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_hni_stage3_provisions() {
		return r0820_non_resident_hni_stage3_provisions;
	}
	public void setR0820_non_resident_hni_stage3_provisions(BigDecimal r0820_non_resident_hni_stage3_provisions) {
		this.r0820_non_resident_hni_stage3_provisions = r0820_non_resident_hni_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_hni_provision_interest_legacy_interest() {
		return r0820_non_resident_hni_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_hni_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_hni_provision_interest_legacy_interest) {
		this.r0820_non_resident_hni_provision_interest_legacy_interest = r0820_non_resident_hni_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_individuals_outstanding_balance() {
		return r0820_non_resident_individuals_outstanding_balance;
	}
	public void setR0820_non_resident_individuals_outstanding_balance(
			BigDecimal r0820_non_resident_individuals_outstanding_balance) {
		this.r0820_non_resident_individuals_outstanding_balance = r0820_non_resident_individuals_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_individuals_loans_stage3() {
		return r0820_non_resident_individuals_loans_stage3;
	}
	public void setR0820_non_resident_individuals_loans_stage3(BigDecimal r0820_non_resident_individuals_loans_stage3) {
		this.r0820_non_resident_individuals_loans_stage3 = r0820_non_resident_individuals_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_individuals_stage3_provisions() {
		return r0820_non_resident_individuals_stage3_provisions;
	}
	public void setR0820_non_resident_individuals_stage3_provisions(
			BigDecimal r0820_non_resident_individuals_stage3_provisions) {
		this.r0820_non_resident_individuals_stage3_provisions = r0820_non_resident_individuals_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_individuals_provision_interest_legacy_interest() {
		return r0820_non_resident_individuals_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_individuals_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_individuals_provision_interest_legacy_interest) {
		this.r0820_non_resident_individuals_provision_interest_legacy_interest = r0820_non_resident_individuals_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_nonbanking_financial_outstanding_balance() {
		return r0820_non_resident_nonbanking_financial_outstanding_balance;
	}
	public void setR0820_non_resident_nonbanking_financial_outstanding_balance(
			BigDecimal r0820_non_resident_nonbanking_financial_outstanding_balance) {
		this.r0820_non_resident_nonbanking_financial_outstanding_balance = r0820_non_resident_nonbanking_financial_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_nonbanking_financial_loans_stage3() {
		return r0820_non_resident_nonbanking_financial_loans_stage3;
	}
	public void setR0820_non_resident_nonbanking_financial_loans_stage3(
			BigDecimal r0820_non_resident_nonbanking_financial_loans_stage3) {
		this.r0820_non_resident_nonbanking_financial_loans_stage3 = r0820_non_resident_nonbanking_financial_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_nonbanking_financial_stage3_provisions() {
		return r0820_non_resident_nonbanking_financial_stage3_provisions;
	}
	public void setR0820_non_resident_nonbanking_financial_stage3_provisions(
			BigDecimal r0820_non_resident_nonbanking_financial_stage3_provisions) {
		this.r0820_non_resident_nonbanking_financial_stage3_provisions = r0820_non_resident_nonbanking_financial_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_nonbanking_financial_provision_interest_legacy_interest() {
		return r0820_non_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_nonbanking_financial_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_nonbanking_financial_provision_interest_legacy_interest) {
		this.r0820_non_resident_nonbanking_financial_provision_interest_legacy_interest = r0820_non_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public BigDecimal getR0820_non_resident_tradebills_outstanding_balance() {
		return r0820_non_resident_tradebills_outstanding_balance;
	}
	public void setR0820_non_resident_tradebills_outstanding_balance(
			BigDecimal r0820_non_resident_tradebills_outstanding_balance) {
		this.r0820_non_resident_tradebills_outstanding_balance = r0820_non_resident_tradebills_outstanding_balance;
	}
	public BigDecimal getR0820_non_resident_tradebills_loans_stage3() {
		return r0820_non_resident_tradebills_loans_stage3;
	}
	public void setR0820_non_resident_tradebills_loans_stage3(BigDecimal r0820_non_resident_tradebills_loans_stage3) {
		this.r0820_non_resident_tradebills_loans_stage3 = r0820_non_resident_tradebills_loans_stage3;
	}
	public BigDecimal getR0820_non_resident_tradebills_stage3_provisions() {
		return r0820_non_resident_tradebills_stage3_provisions;
	}
	public void setR0820_non_resident_tradebills_stage3_provisions(
			BigDecimal r0820_non_resident_tradebills_stage3_provisions) {
		this.r0820_non_resident_tradebills_stage3_provisions = r0820_non_resident_tradebills_stage3_provisions;
	}
	public BigDecimal getR0820_non_resident_tradebills_provision_interest_legacy_interest() {
		return r0820_non_resident_tradebills_provision_interest_legacy_interest;
	}
	public void setR0820_non_resident_tradebills_provision_interest_legacy_interest(
			BigDecimal r0820_non_resident_tradebills_provision_interest_legacy_interest) {
		this.r0820_non_resident_tradebills_provision_interest_legacy_interest = r0820_non_resident_tradebills_provision_interest_legacy_interest;
	}
	public String getR0830_resident_item() {
		return r0830_resident_item;
	}
	public void setR0830_resident_item(String r0830_resident_item) {
		this.r0830_resident_item = r0830_resident_item;
	}
	public BigDecimal getR0830_resident_government_private_sector_outstanding_balance() {
		return r0830_resident_government_private_sector_outstanding_balance;
	}
	public void setR0830_resident_government_private_sector_outstanding_balance(
			BigDecimal r0830_resident_government_private_sector_outstanding_balance) {
		this.r0830_resident_government_private_sector_outstanding_balance = r0830_resident_government_private_sector_outstanding_balance;
	}
	public BigDecimal getR0830_resident_government_private_sector_loans_stage3() {
		return r0830_resident_government_private_sector_loans_stage3;
	}
	public void setR0830_resident_government_private_sector_loans_stage3(
			BigDecimal r0830_resident_government_private_sector_loans_stage3) {
		this.r0830_resident_government_private_sector_loans_stage3 = r0830_resident_government_private_sector_loans_stage3;
	}
	public BigDecimal getR0830_resident_government_private_sector_stage3_provisions() {
		return r0830_resident_government_private_sector_stage3_provisions;
	}
	public void setR0830_resident_government_private_sector_stage3_provisions(
			BigDecimal r0830_resident_government_private_sector_stage3_provisions) {
		this.r0830_resident_government_private_sector_stage3_provisions = r0830_resident_government_private_sector_stage3_provisions;
	}
	public BigDecimal getR0830_resident_government_private_sector_provision_interest_legacy_interest() {
		return r0830_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public void setR0830_resident_government_private_sector_provision_interest_legacy_interest(
			BigDecimal r0830_resident_government_private_sector_provision_interest_legacy_interest) {
		this.r0830_resident_government_private_sector_provision_interest_legacy_interest = r0830_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_gre_outstanding_balance() {
		return r0830_resident_gre_outstanding_balance;
	}
	public void setR0830_resident_gre_outstanding_balance(BigDecimal r0830_resident_gre_outstanding_balance) {
		this.r0830_resident_gre_outstanding_balance = r0830_resident_gre_outstanding_balance;
	}
	public BigDecimal getR0830_resident_gre_loans_stage3() {
		return r0830_resident_gre_loans_stage3;
	}
	public void setR0830_resident_gre_loans_stage3(BigDecimal r0830_resident_gre_loans_stage3) {
		this.r0830_resident_gre_loans_stage3 = r0830_resident_gre_loans_stage3;
	}
	public BigDecimal getR0830_resident_gre_stage3_provisions() {
		return r0830_resident_gre_stage3_provisions;
	}
	public void setR0830_resident_gre_stage3_provisions(BigDecimal r0830_resident_gre_stage3_provisions) {
		this.r0830_resident_gre_stage3_provisions = r0830_resident_gre_stage3_provisions;
	}
	public BigDecimal getR0830_resident_gre_provision_interest_legacy_interest() {
		return r0830_resident_gre_provision_interest_legacy_interest;
	}
	public void setR0830_resident_gre_provision_interest_legacy_interest(
			BigDecimal r0830_resident_gre_provision_interest_legacy_interest) {
		this.r0830_resident_gre_provision_interest_legacy_interest = r0830_resident_gre_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_private_sector_outstanding_balance() {
		return r0830_resident_private_sector_outstanding_balance;
	}
	public void setR0830_resident_private_sector_outstanding_balance(
			BigDecimal r0830_resident_private_sector_outstanding_balance) {
		this.r0830_resident_private_sector_outstanding_balance = r0830_resident_private_sector_outstanding_balance;
	}
	public BigDecimal getR0830_resident_private_sector_loans_stage3() {
		return r0830_resident_private_sector_loans_stage3;
	}
	public void setR0830_resident_private_sector_loans_stage3(BigDecimal r0830_resident_private_sector_loans_stage3) {
		this.r0830_resident_private_sector_loans_stage3 = r0830_resident_private_sector_loans_stage3;
	}
	public BigDecimal getR0830_resident_private_sector_stage3_provisions() {
		return r0830_resident_private_sector_stage3_provisions;
	}
	public void setR0830_resident_private_sector_stage3_provisions(
			BigDecimal r0830_resident_private_sector_stage3_provisions) {
		this.r0830_resident_private_sector_stage3_provisions = r0830_resident_private_sector_stage3_provisions;
	}
	public BigDecimal getR0830_resident_private_sector_provision_interest_legacy_interest() {
		return r0830_resident_private_sector_provision_interest_legacy_interest;
	}
	public void setR0830_resident_private_sector_provision_interest_legacy_interest(
			BigDecimal r0830_resident_private_sector_provision_interest_legacy_interest) {
		this.r0830_resident_private_sector_provision_interest_legacy_interest = r0830_resident_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_sme_outstanding_balance() {
		return r0830_resident_sme_outstanding_balance;
	}
	public void setR0830_resident_sme_outstanding_balance(BigDecimal r0830_resident_sme_outstanding_balance) {
		this.r0830_resident_sme_outstanding_balance = r0830_resident_sme_outstanding_balance;
	}
	public BigDecimal getR0830_resident_sme_loans_stage3() {
		return r0830_resident_sme_loans_stage3;
	}
	public void setR0830_resident_sme_loans_stage3(BigDecimal r0830_resident_sme_loans_stage3) {
		this.r0830_resident_sme_loans_stage3 = r0830_resident_sme_loans_stage3;
	}
	public BigDecimal getR0830_resident_sme_stage3_provisions() {
		return r0830_resident_sme_stage3_provisions;
	}
	public void setR0830_resident_sme_stage3_provisions(BigDecimal r0830_resident_sme_stage3_provisions) {
		this.r0830_resident_sme_stage3_provisions = r0830_resident_sme_stage3_provisions;
	}
	public BigDecimal getR0830_resident_sme_provision_interest_legacy_interest() {
		return r0830_resident_sme_provision_interest_legacy_interest;
	}
	public void setR0830_resident_sme_provision_interest_legacy_interest(
			BigDecimal r0830_resident_sme_provision_interest_legacy_interest) {
		this.r0830_resident_sme_provision_interest_legacy_interest = r0830_resident_sme_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_hni_outstanding_balance() {
		return r0830_resident_hni_outstanding_balance;
	}
	public void setR0830_resident_hni_outstanding_balance(BigDecimal r0830_resident_hni_outstanding_balance) {
		this.r0830_resident_hni_outstanding_balance = r0830_resident_hni_outstanding_balance;
	}
	public BigDecimal getR0830_resident_hni_loans_stage3() {
		return r0830_resident_hni_loans_stage3;
	}
	public void setR0830_resident_hni_loans_stage3(BigDecimal r0830_resident_hni_loans_stage3) {
		this.r0830_resident_hni_loans_stage3 = r0830_resident_hni_loans_stage3;
	}
	public BigDecimal getR0830_resident_hni_stage3_provisions() {
		return r0830_resident_hni_stage3_provisions;
	}
	public void setR0830_resident_hni_stage3_provisions(BigDecimal r0830_resident_hni_stage3_provisions) {
		this.r0830_resident_hni_stage3_provisions = r0830_resident_hni_stage3_provisions;
	}
	public BigDecimal getR0830_resident_hni_provision_interest_legacy_interest() {
		return r0830_resident_hni_provision_interest_legacy_interest;
	}
	public void setR0830_resident_hni_provision_interest_legacy_interest(
			BigDecimal r0830_resident_hni_provision_interest_legacy_interest) {
		this.r0830_resident_hni_provision_interest_legacy_interest = r0830_resident_hni_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_individuals_outstanding_balance() {
		return r0830_resident_individuals_outstanding_balance;
	}
	public void setR0830_resident_individuals_outstanding_balance(
			BigDecimal r0830_resident_individuals_outstanding_balance) {
		this.r0830_resident_individuals_outstanding_balance = r0830_resident_individuals_outstanding_balance;
	}
	public BigDecimal getR0830_resident_individuals_loans_stage3() {
		return r0830_resident_individuals_loans_stage3;
	}
	public void setR0830_resident_individuals_loans_stage3(BigDecimal r0830_resident_individuals_loans_stage3) {
		this.r0830_resident_individuals_loans_stage3 = r0830_resident_individuals_loans_stage3;
	}
	public BigDecimal getR0830_resident_individuals_stage3_provisions() {
		return r0830_resident_individuals_stage3_provisions;
	}
	public void setR0830_resident_individuals_stage3_provisions(BigDecimal r0830_resident_individuals_stage3_provisions) {
		this.r0830_resident_individuals_stage3_provisions = r0830_resident_individuals_stage3_provisions;
	}
	public BigDecimal getR0830_resident_individuals_provision_interest_legacy_interest() {
		return r0830_resident_individuals_provision_interest_legacy_interest;
	}
	public void setR0830_resident_individuals_provision_interest_legacy_interest(
			BigDecimal r0830_resident_individuals_provision_interest_legacy_interest) {
		this.r0830_resident_individuals_provision_interest_legacy_interest = r0830_resident_individuals_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_nonbanking_financial_outstanding_balance() {
		return r0830_resident_nonbanking_financial_outstanding_balance;
	}
	public void setR0830_resident_nonbanking_financial_outstanding_balance(
			BigDecimal r0830_resident_nonbanking_financial_outstanding_balance) {
		this.r0830_resident_nonbanking_financial_outstanding_balance = r0830_resident_nonbanking_financial_outstanding_balance;
	}
	public BigDecimal getR0830_resident_nonbanking_financial_loans_stage3() {
		return r0830_resident_nonbanking_financial_loans_stage3;
	}
	public void setR0830_resident_nonbanking_financial_loans_stage3(
			BigDecimal r0830_resident_nonbanking_financial_loans_stage3) {
		this.r0830_resident_nonbanking_financial_loans_stage3 = r0830_resident_nonbanking_financial_loans_stage3;
	}
	public BigDecimal getR0830_resident_nonbanking_financial_stage3_provisions() {
		return r0830_resident_nonbanking_financial_stage3_provisions;
	}
	public void setR0830_resident_nonbanking_financial_stage3_provisions(
			BigDecimal r0830_resident_nonbanking_financial_stage3_provisions) {
		this.r0830_resident_nonbanking_financial_stage3_provisions = r0830_resident_nonbanking_financial_stage3_provisions;
	}
	public BigDecimal getR0830_resident_nonbanking_financial_provision_interest_legacy_interest() {
		return r0830_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public void setR0830_resident_nonbanking_financial_provision_interest_legacy_interest(
			BigDecimal r0830_resident_nonbanking_financial_provision_interest_legacy_interest) {
		this.r0830_resident_nonbanking_financial_provision_interest_legacy_interest = r0830_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_resident_tradebills_outstanding_balance() {
		return r0830_resident_tradebills_outstanding_balance;
	}
	public void setR0830_resident_tradebills_outstanding_balance(BigDecimal r0830_resident_tradebills_outstanding_balance) {
		this.r0830_resident_tradebills_outstanding_balance = r0830_resident_tradebills_outstanding_balance;
	}
	public BigDecimal getR0830_resident_tradebills_loans_stage3() {
		return r0830_resident_tradebills_loans_stage3;
	}
	public void setR0830_resident_tradebills_loans_stage3(BigDecimal r0830_resident_tradebills_loans_stage3) {
		this.r0830_resident_tradebills_loans_stage3 = r0830_resident_tradebills_loans_stage3;
	}
	public BigDecimal getR0830_resident_tradebills_stage3_provisions() {
		return r0830_resident_tradebills_stage3_provisions;
	}
	public void setR0830_resident_tradebills_stage3_provisions(BigDecimal r0830_resident_tradebills_stage3_provisions) {
		this.r0830_resident_tradebills_stage3_provisions = r0830_resident_tradebills_stage3_provisions;
	}
	public BigDecimal getR0830_resident_tradebills_provision_interest_legacy_interest() {
		return r0830_resident_tradebills_provision_interest_legacy_interest;
	}
	public void setR0830_resident_tradebills_provision_interest_legacy_interest(
			BigDecimal r0830_resident_tradebills_provision_interest_legacy_interest) {
		this.r0830_resident_tradebills_provision_interest_legacy_interest = r0830_resident_tradebills_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_government_private_sector_outstanding_balance() {
		return r0830_non_resident_government_private_sector_outstanding_balance;
	}
	public void setR0830_non_resident_government_private_sector_outstanding_balance(
			BigDecimal r0830_non_resident_government_private_sector_outstanding_balance) {
		this.r0830_non_resident_government_private_sector_outstanding_balance = r0830_non_resident_government_private_sector_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_government_private_sector_loans_stage3() {
		return r0830_non_resident_government_private_sector_loans_stage3;
	}
	public void setR0830_non_resident_government_private_sector_loans_stage3(
			BigDecimal r0830_non_resident_government_private_sector_loans_stage3) {
		this.r0830_non_resident_government_private_sector_loans_stage3 = r0830_non_resident_government_private_sector_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_government_private_sector_stage3_provisions() {
		return r0830_non_resident_government_private_sector_stage3_provisions;
	}
	public void setR0830_non_resident_government_private_sector_stage3_provisions(
			BigDecimal r0830_non_resident_government_private_sector_stage3_provisions) {
		this.r0830_non_resident_government_private_sector_stage3_provisions = r0830_non_resident_government_private_sector_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_government_private_sector_provision_interest_legacy_interest() {
		return r0830_non_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_government_private_sector_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_government_private_sector_provision_interest_legacy_interest) {
		this.r0830_non_resident_government_private_sector_provision_interest_legacy_interest = r0830_non_resident_government_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_gre_outstanding_balance() {
		return r0830_non_resident_gre_outstanding_balance;
	}
	public void setR0830_non_resident_gre_outstanding_balance(BigDecimal r0830_non_resident_gre_outstanding_balance) {
		this.r0830_non_resident_gre_outstanding_balance = r0830_non_resident_gre_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_gre_loans_stage3() {
		return r0830_non_resident_gre_loans_stage3;
	}
	public void setR0830_non_resident_gre_loans_stage3(BigDecimal r0830_non_resident_gre_loans_stage3) {
		this.r0830_non_resident_gre_loans_stage3 = r0830_non_resident_gre_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_gre_stage3_provisions() {
		return r0830_non_resident_gre_stage3_provisions;
	}
	public void setR0830_non_resident_gre_stage3_provisions(BigDecimal r0830_non_resident_gre_stage3_provisions) {
		this.r0830_non_resident_gre_stage3_provisions = r0830_non_resident_gre_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_gre_provision_interest_legacy_interest() {
		return r0830_non_resident_gre_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_gre_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_gre_provision_interest_legacy_interest) {
		this.r0830_non_resident_gre_provision_interest_legacy_interest = r0830_non_resident_gre_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_private_sector_outstanding_balance() {
		return r0830_non_resident_private_sector_outstanding_balance;
	}
	public void setR0830_non_resident_private_sector_outstanding_balance(
			BigDecimal r0830_non_resident_private_sector_outstanding_balance) {
		this.r0830_non_resident_private_sector_outstanding_balance = r0830_non_resident_private_sector_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_private_sector_loans_stage3() {
		return r0830_non_resident_private_sector_loans_stage3;
	}
	public void setR0830_non_resident_private_sector_loans_stage3(
			BigDecimal r0830_non_resident_private_sector_loans_stage3) {
		this.r0830_non_resident_private_sector_loans_stage3 = r0830_non_resident_private_sector_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_private_sector_stage3_provisions() {
		return r0830_non_resident_private_sector_stage3_provisions;
	}
	public void setR0830_non_resident_private_sector_stage3_provisions(
			BigDecimal r0830_non_resident_private_sector_stage3_provisions) {
		this.r0830_non_resident_private_sector_stage3_provisions = r0830_non_resident_private_sector_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_private_sector_provision_interest_legacy_interest() {
		return r0830_non_resident_private_sector_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_private_sector_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_private_sector_provision_interest_legacy_interest) {
		this.r0830_non_resident_private_sector_provision_interest_legacy_interest = r0830_non_resident_private_sector_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_sme_outstanding_balance() {
		return r0830_non_resident_sme_outstanding_balance;
	}
	public void setR0830_non_resident_sme_outstanding_balance(BigDecimal r0830_non_resident_sme_outstanding_balance) {
		this.r0830_non_resident_sme_outstanding_balance = r0830_non_resident_sme_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_sme_loans_stage3() {
		return r0830_non_resident_sme_loans_stage3;
	}
	public void setR0830_non_resident_sme_loans_stage3(BigDecimal r0830_non_resident_sme_loans_stage3) {
		this.r0830_non_resident_sme_loans_stage3 = r0830_non_resident_sme_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_sme_stage3_provisions() {
		return r0830_non_resident_sme_stage3_provisions;
	}
	public void setR0830_non_resident_sme_stage3_provisions(BigDecimal r0830_non_resident_sme_stage3_provisions) {
		this.r0830_non_resident_sme_stage3_provisions = r0830_non_resident_sme_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_sme_provision_interest_legacy_interest() {
		return r0830_non_resident_sme_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_sme_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_sme_provision_interest_legacy_interest) {
		this.r0830_non_resident_sme_provision_interest_legacy_interest = r0830_non_resident_sme_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_hni_outstanding_balance() {
		return r0830_non_resident_hni_outstanding_balance;
	}
	public void setR0830_non_resident_hni_outstanding_balance(BigDecimal r0830_non_resident_hni_outstanding_balance) {
		this.r0830_non_resident_hni_outstanding_balance = r0830_non_resident_hni_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_hni_loans_stage3() {
		return r0830_non_resident_hni_loans_stage3;
	}
	public void setR0830_non_resident_hni_loans_stage3(BigDecimal r0830_non_resident_hni_loans_stage3) {
		this.r0830_non_resident_hni_loans_stage3 = r0830_non_resident_hni_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_hni_stage3_provisions() {
		return r0830_non_resident_hni_stage3_provisions;
	}
	public void setR0830_non_resident_hni_stage3_provisions(BigDecimal r0830_non_resident_hni_stage3_provisions) {
		this.r0830_non_resident_hni_stage3_provisions = r0830_non_resident_hni_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_hni_provision_interest_legacy_interest() {
		return r0830_non_resident_hni_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_hni_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_hni_provision_interest_legacy_interest) {
		this.r0830_non_resident_hni_provision_interest_legacy_interest = r0830_non_resident_hni_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_individuals_outstanding_balance() {
		return r0830_non_resident_individuals_outstanding_balance;
	}
	public void setR0830_non_resident_individuals_outstanding_balance(
			BigDecimal r0830_non_resident_individuals_outstanding_balance) {
		this.r0830_non_resident_individuals_outstanding_balance = r0830_non_resident_individuals_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_individuals_loans_stage3() {
		return r0830_non_resident_individuals_loans_stage3;
	}
	public void setR0830_non_resident_individuals_loans_stage3(BigDecimal r0830_non_resident_individuals_loans_stage3) {
		this.r0830_non_resident_individuals_loans_stage3 = r0830_non_resident_individuals_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_individuals_stage3_provisions() {
		return r0830_non_resident_individuals_stage3_provisions;
	}
	public void setR0830_non_resident_individuals_stage3_provisions(
			BigDecimal r0830_non_resident_individuals_stage3_provisions) {
		this.r0830_non_resident_individuals_stage3_provisions = r0830_non_resident_individuals_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_individuals_provision_interest_legacy_interest() {
		return r0830_non_resident_individuals_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_individuals_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_individuals_provision_interest_legacy_interest) {
		this.r0830_non_resident_individuals_provision_interest_legacy_interest = r0830_non_resident_individuals_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_nonbanking_financial_outstanding_balance() {
		return r0830_non_resident_nonbanking_financial_outstanding_balance;
	}
	public void setR0830_non_resident_nonbanking_financial_outstanding_balance(
			BigDecimal r0830_non_resident_nonbanking_financial_outstanding_balance) {
		this.r0830_non_resident_nonbanking_financial_outstanding_balance = r0830_non_resident_nonbanking_financial_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_nonbanking_financial_loans_stage3() {
		return r0830_non_resident_nonbanking_financial_loans_stage3;
	}
	public void setR0830_non_resident_nonbanking_financial_loans_stage3(
			BigDecimal r0830_non_resident_nonbanking_financial_loans_stage3) {
		this.r0830_non_resident_nonbanking_financial_loans_stage3 = r0830_non_resident_nonbanking_financial_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_nonbanking_financial_stage3_provisions() {
		return r0830_non_resident_nonbanking_financial_stage3_provisions;
	}
	public void setR0830_non_resident_nonbanking_financial_stage3_provisions(
			BigDecimal r0830_non_resident_nonbanking_financial_stage3_provisions) {
		this.r0830_non_resident_nonbanking_financial_stage3_provisions = r0830_non_resident_nonbanking_financial_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_nonbanking_financial_provision_interest_legacy_interest() {
		return r0830_non_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_nonbanking_financial_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_nonbanking_financial_provision_interest_legacy_interest) {
		this.r0830_non_resident_nonbanking_financial_provision_interest_legacy_interest = r0830_non_resident_nonbanking_financial_provision_interest_legacy_interest;
	}
	public BigDecimal getR0830_non_resident_tradebills_outstanding_balance() {
		return r0830_non_resident_tradebills_outstanding_balance;
	}
	public void setR0830_non_resident_tradebills_outstanding_balance(
			BigDecimal r0830_non_resident_tradebills_outstanding_balance) {
		this.r0830_non_resident_tradebills_outstanding_balance = r0830_non_resident_tradebills_outstanding_balance;
	}
	public BigDecimal getR0830_non_resident_tradebills_loans_stage3() {
		return r0830_non_resident_tradebills_loans_stage3;
	}
	public void setR0830_non_resident_tradebills_loans_stage3(BigDecimal r0830_non_resident_tradebills_loans_stage3) {
		this.r0830_non_resident_tradebills_loans_stage3 = r0830_non_resident_tradebills_loans_stage3;
	}
	public BigDecimal getR0830_non_resident_tradebills_stage3_provisions() {
		return r0830_non_resident_tradebills_stage3_provisions;
	}
	public void setR0830_non_resident_tradebills_stage3_provisions(
			BigDecimal r0830_non_resident_tradebills_stage3_provisions) {
		this.r0830_non_resident_tradebills_stage3_provisions = r0830_non_resident_tradebills_stage3_provisions;
	}
	public BigDecimal getR0830_non_resident_tradebills_provision_interest_legacy_interest() {
		return r0830_non_resident_tradebills_provision_interest_legacy_interest;
	}
	public void setR0830_non_resident_tradebills_provision_interest_legacy_interest(
			BigDecimal r0830_non_resident_tradebills_provision_interest_legacy_interest) {
		this.r0830_non_resident_tradebills_provision_interest_legacy_interest = r0830_non_resident_tradebills_provision_interest_legacy_interest;
	}
	public Date getReport_date() {
		return report_date;
	}
	public void setReport_date(Date report_date) {
		this.report_date = report_date;
	}
	public String getReport_version() {
		return report_version;
	}
	public void setReport_version(String report_version) {
		this.report_version = report_version;
	}
	public String getReport_frequency() {
		return report_frequency;
	}
	public void setReport_frequency(String report_frequency) {
		this.report_frequency = report_frequency;
	}
	public String getReport_code() {
		return report_code;
	}
	public void setReport_code(String report_code) {
		this.report_code = report_code;
	}
	public String getReport_desc() {
		return report_desc;
	}
	public void setReport_desc(String report_desc) {
		this.report_desc = report_desc;
	}
	public String getEntity_flg() {
		return entity_flg;
	}
	public void setEntity_flg(String entity_flg) {
		this.entity_flg = entity_flg;
	}
	public String getModify_flg() {
		return modify_flg;
	}
	public void setModify_flg(String modify_flg) {
		this.modify_flg = modify_flg;
	}
	public String getDel_flg() {
		return del_flg;
	}
	public void setDel_flg(String del_flg) {
		this.del_flg = del_flg;
	}


}
