package com.bornfire.brf.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "CBUAE_BRF7_3_SUMMARYTABLE5")
public class CBUAE_BRF7_3_Summary_Entity5 {

	private  String  R0860_PRODUCT;
	private  String  R0870_1_TO_3_YEARS_NAT_AMT;
	private  String  R0870_BOUGHT_HEDG_NET_DELTA_POS;
	private  String  R0870_BOUGHT_TRAD_NET_DELTA_POS;
	private  String  R0870_GROSS_MKT_VAL;
	private  String  R0870_HEDG_NAT_AMT;
	private  String  R0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0870_NAT_AMT;
	private  String  R0870_NON_RES_NAT_AMT;
	private  String  R0870_OVER_3_YEARS_NAT_AMT;
	private  String  R0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0870_PRODUCT;
	private  String  R0870_PRO_BOUGHT_NET_GAIN_LOSS;
	private  String  R0870_PRO_SOLD_NET_GAIN_LOSS;
	private  String  R0870_RES_1_TO_3_YEARS_MKT_VAL;
	private  String  R0870_RES_LESSTHAN_1_YEAR_MKT_VAL;
	private  String  R0870_RES_MORETHAN_3_YEARS_MKT_VAL;
	private  String  R0870_RES_NAT_AMT;
	private  String  R0870_SOLD_HEDG_NET_DELTA_POS;
	private  String  R0870_SOLD_TRAD_NET_DELTA_POS;
	private  String  R0870_TRAD_NAT_AMT;
	private  String  R0870_WITHIN_1_YEAR_NAT_AMT;
	private  String  REPORT_CODE;
	@Id
	private  String  REPORT_DATE;
	private  String  REPORT_DESC;
	private  String  REPORT_FREQUENCY;
	private  String  REPORT_VERSION;
	public String getR0860_PRODUCT() {
		return R0860_PRODUCT;
	}
	public void setR0860_PRODUCT(String r0860_PRODUCT) {
		R0860_PRODUCT = r0860_PRODUCT;
	}
	public String getR0870_1_TO_3_YEARS_NAT_AMT() {
		return R0870_1_TO_3_YEARS_NAT_AMT;
	}
	public void setR0870_1_TO_3_YEARS_NAT_AMT(String r0870_1_TO_3_YEARS_NAT_AMT) {
		R0870_1_TO_3_YEARS_NAT_AMT = r0870_1_TO_3_YEARS_NAT_AMT;
	}
	public String getR0870_BOUGHT_HEDG_NET_DELTA_POS() {
		return R0870_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public void setR0870_BOUGHT_HEDG_NET_DELTA_POS(String r0870_BOUGHT_HEDG_NET_DELTA_POS) {
		R0870_BOUGHT_HEDG_NET_DELTA_POS = r0870_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public String getR0870_BOUGHT_TRAD_NET_DELTA_POS() {
		return R0870_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public void setR0870_BOUGHT_TRAD_NET_DELTA_POS(String r0870_BOUGHT_TRAD_NET_DELTA_POS) {
		R0870_BOUGHT_TRAD_NET_DELTA_POS = r0870_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public String getR0870_GROSS_MKT_VAL() {
		return R0870_GROSS_MKT_VAL;
	}
	public void setR0870_GROSS_MKT_VAL(String r0870_GROSS_MKT_VAL) {
		R0870_GROSS_MKT_VAL = r0870_GROSS_MKT_VAL;
	}
	public String getR0870_HEDG_NAT_AMT() {
		return R0870_HEDG_NAT_AMT;
	}
	public void setR0870_HEDG_NAT_AMT(String r0870_HEDG_NAT_AMT) {
		R0870_HEDG_NAT_AMT = r0870_HEDG_NAT_AMT;
	}
	public String getR0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0870_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0870_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0870_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0870_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0870_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0870_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0870_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0870_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0870_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0870_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0870_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0870_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0870_NAT_AMT() {
		return R0870_NAT_AMT;
	}
	public void setR0870_NAT_AMT(String r0870_NAT_AMT) {
		R0870_NAT_AMT = r0870_NAT_AMT;
	}
	public String getR0870_NON_RES_NAT_AMT() {
		return R0870_NON_RES_NAT_AMT;
	}
	public void setR0870_NON_RES_NAT_AMT(String r0870_NON_RES_NAT_AMT) {
		R0870_NON_RES_NAT_AMT = r0870_NON_RES_NAT_AMT;
	}
	public String getR0870_OVER_3_YEARS_NAT_AMT() {
		return R0870_OVER_3_YEARS_NAT_AMT;
	}
	public void setR0870_OVER_3_YEARS_NAT_AMT(String r0870_OVER_3_YEARS_NAT_AMT) {
		R0870_OVER_3_YEARS_NAT_AMT = r0870_OVER_3_YEARS_NAT_AMT;
	}
	public String getR0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0870_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0870_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0870_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0870_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0870_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0870_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0870_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0870_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0870_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0870_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0870_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0870_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0870_PRODUCT() {
		return R0870_PRODUCT;
	}
	public void setR0870_PRODUCT(String r0870_PRODUCT) {
		R0870_PRODUCT = r0870_PRODUCT;
	}
	public String getR0870_PRO_BOUGHT_NET_GAIN_LOSS() {
		return R0870_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public void setR0870_PRO_BOUGHT_NET_GAIN_LOSS(String r0870_PRO_BOUGHT_NET_GAIN_LOSS) {
		R0870_PRO_BOUGHT_NET_GAIN_LOSS = r0870_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public String getR0870_PRO_SOLD_NET_GAIN_LOSS() {
		return R0870_PRO_SOLD_NET_GAIN_LOSS;
	}
	public void setR0870_PRO_SOLD_NET_GAIN_LOSS(String r0870_PRO_SOLD_NET_GAIN_LOSS) {
		R0870_PRO_SOLD_NET_GAIN_LOSS = r0870_PRO_SOLD_NET_GAIN_LOSS;
	}
	public String getR0870_RES_1_TO_3_YEARS_MKT_VAL() {
		return R0870_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public void setR0870_RES_1_TO_3_YEARS_MKT_VAL(String r0870_RES_1_TO_3_YEARS_MKT_VAL) {
		R0870_RES_1_TO_3_YEARS_MKT_VAL = r0870_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public String getR0870_RES_LESSTHAN_1_YEAR_MKT_VAL() {
		return R0870_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public void setR0870_RES_LESSTHAN_1_YEAR_MKT_VAL(String r0870_RES_LESSTHAN_1_YEAR_MKT_VAL) {
		R0870_RES_LESSTHAN_1_YEAR_MKT_VAL = r0870_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public String getR0870_RES_MORETHAN_3_YEARS_MKT_VAL() {
		return R0870_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public void setR0870_RES_MORETHAN_3_YEARS_MKT_VAL(String r0870_RES_MORETHAN_3_YEARS_MKT_VAL) {
		R0870_RES_MORETHAN_3_YEARS_MKT_VAL = r0870_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public String getR0870_RES_NAT_AMT() {
		return R0870_RES_NAT_AMT;
	}
	public void setR0870_RES_NAT_AMT(String r0870_RES_NAT_AMT) {
		R0870_RES_NAT_AMT = r0870_RES_NAT_AMT;
	}
	public String getR0870_SOLD_HEDG_NET_DELTA_POS() {
		return R0870_SOLD_HEDG_NET_DELTA_POS;
	}
	public void setR0870_SOLD_HEDG_NET_DELTA_POS(String r0870_SOLD_HEDG_NET_DELTA_POS) {
		R0870_SOLD_HEDG_NET_DELTA_POS = r0870_SOLD_HEDG_NET_DELTA_POS;
	}
	public String getR0870_SOLD_TRAD_NET_DELTA_POS() {
		return R0870_SOLD_TRAD_NET_DELTA_POS;
	}
	public void setR0870_SOLD_TRAD_NET_DELTA_POS(String r0870_SOLD_TRAD_NET_DELTA_POS) {
		R0870_SOLD_TRAD_NET_DELTA_POS = r0870_SOLD_TRAD_NET_DELTA_POS;
	}
	public String getR0870_TRAD_NAT_AMT() {
		return R0870_TRAD_NAT_AMT;
	}
	public void setR0870_TRAD_NAT_AMT(String r0870_TRAD_NAT_AMT) {
		R0870_TRAD_NAT_AMT = r0870_TRAD_NAT_AMT;
	}
	public String getR0870_WITHIN_1_YEAR_NAT_AMT() {
		return R0870_WITHIN_1_YEAR_NAT_AMT;
	}
	public void setR0870_WITHIN_1_YEAR_NAT_AMT(String r0870_WITHIN_1_YEAR_NAT_AMT) {
		R0870_WITHIN_1_YEAR_NAT_AMT = r0870_WITHIN_1_YEAR_NAT_AMT;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(String rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public String getREPORT_DESC() {
		return REPORT_DESC;
	}
	public void setREPORT_DESC(String rEPORT_DESC) {
		REPORT_DESC = rEPORT_DESC;
	}
	public String getREPORT_FREQUENCY() {
		return REPORT_FREQUENCY;
	}
	public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
		REPORT_FREQUENCY = rEPORT_FREQUENCY;
	}
	public String getREPORT_VERSION() {
		return REPORT_VERSION;
	}
	public void setREPORT_VERSION(String rEPORT_VERSION) {
		REPORT_VERSION = rEPORT_VERSION;
	}
	public CBUAE_BRF7_3_Summary_Entity5() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
