package com.bornfire.brf.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "CBUAE_BRF7_3_SUMMARYTABLE4")
public class CBUAE_BRF7_3_Summary_Entity4 {

	private  String  R0820_1_TO_3_YEARS_NAT_AMT;
	private  String  R0820_BOUGHT_HEDG_NET_DELTA_POS;
	private  String  R0820_BOUGHT_TRAD_NET_DELTA_POS;
	private  String  R0820_GROSS_MKT_VAL;
	private  String  R0820_HEDG_NAT_AMT;
	private  String  R0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0820_NAT_AMT;
	private  String  R0820_NON_RES_NAT_AMT;
	private  String  R0820_OVER_3_YEARS_NAT_AMT;
	private  String  R0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0820_PRODUCT;
	private  String  R0820_PRO_BOUGHT_NET_GAIN_LOSS;
	private  String  R0820_PRO_SOLD_NET_GAIN_LOSS;
	private  String  R0820_RES_1_TO_3_YEARS_MKT_VAL;
	private  String  R0820_RES_LESSTHAN_1_YEAR_MKT_VAL;
	private  String  R0820_RES_MORETHAN_3_YEARS_MKT_VAL;
	private  String  R0820_RES_NAT_AMT;
	private  String  R0820_SOLD_HEDG_NET_DELTA_POS;
	private  String  R0820_SOLD_TRAD_NET_DELTA_POS;
	private  String  R0820_TRAD_NAT_AMT;
	private  String  R0820_WITHIN_1_YEAR_NAT_AMT;
	private  String  R0830_1_TO_3_YEARS_NAT_AMT;
	private  String  R0830_BOUGHT_HEDG_NET_DELTA_POS;
	private  String  R0830_BOUGHT_TRAD_NET_DELTA_POS;
	private  String  R0830_GROSS_MKT_VAL;
	private  String  R0830_HEDG_NAT_AMT;
	private  String  R0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0830_NAT_AMT;
	private  String  R0830_NON_RES_NAT_AMT;
	private  String  R0830_OVER_3_YEARS_NAT_AMT;
	private  String  R0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0830_PRODUCT;
	private  String  R0830_PRO_BOUGHT_NET_GAIN_LOSS;
	private  String  R0830_PRO_SOLD_NET_GAIN_LOSS;
	private  String  R0830_RES_1_TO_3_YEARS_MKT_VAL;
	private  String  R0830_RES_LESSTHAN_1_YEAR_MKT_VAL;
	private  String  R0830_RES_MORETHAN_3_YEARS_MKT_VAL;
	private  String  R0830_RES_NAT_AMT;
	private  String  R0830_SOLD_HEDG_NET_DELTA_POS;
	private  String  R0830_SOLD_TRAD_NET_DELTA_POS;
	private  String  R0830_TRAD_NAT_AMT;
	private  String  R0830_WITHIN_1_YEAR_NAT_AMT;
	private  String  R0840_1_TO_3_YEARS_NAT_AMT;
	private  String  R0840_BOUGHT_HEDG_NET_DELTA_POS;
	private  String  R0840_BOUGHT_TRAD_NET_DELTA_POS;
	private  String  R0840_GROSS_MKT_VAL;
	private  String  R0840_HEDG_NAT_AMT;
	private  String  R0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0840_NAT_AMT;
	private  String  R0840_NON_RES_NAT_AMT;
	private  String  R0840_OVER_3_YEARS_NAT_AMT;
	private  String  R0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0840_PRODUCT;
	private  String  R0840_PRO_BOUGHT_NET_GAIN_LOSS;
	private  String  R0840_PRO_SOLD_NET_GAIN_LOSS;
	private  String  R0840_RES_1_TO_3_YEARS_MKT_VAL;
	private  String  R0840_RES_LESSTHAN_1_YEAR_MKT_VAL;
	private  String  R0840_RES_MORETHAN_3_YEARS_MKT_VAL;
	private  String  R0840_RES_NAT_AMT;
	private  String  R0840_SOLD_HEDG_NET_DELTA_POS;
	private  String  R0840_SOLD_TRAD_NET_DELTA_POS;
	private  String  R0840_TRAD_NAT_AMT;
	private  String  R0840_WITHIN_1_YEAR_NAT_AMT;
	private  String  R0850_1_TO_3_YEARS_NAT_AMT;
	private  String  R0850_BOUGHT_HEDG_NET_DELTA_POS;
	private  String  R0850_BOUGHT_TRAD_NET_DELTA_POS;
	private  String  R0850_GROSS_MKT_VAL;
	private  String  R0850_HEDG_NAT_AMT;
	private  String  R0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0850_NAT_AMT;
	private  String  R0850_NON_RES_NAT_AMT;
	private  String  R0850_OVER_3_YEARS_NAT_AMT;
	private  String  R0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0850_PRODUCT;
	private  String  R0850_PRO_BOUGHT_NET_GAIN_LOSS;
	private  String  R0850_PRO_SOLD_NET_GAIN_LOSS;
	private  String  R0850_RES_1_TO_3_YEARS_MKT_VAL;
	private  String  R0850_RES_LESSTHAN_1_YEAR_MKT_VAL;
	private  String  R0850_RES_MORETHAN_3_YEARS_MKT_VAL;
	private  String  R0850_RES_NAT_AMT;
	private  String  R0850_SOLD_HEDG_NET_DELTA_POS;
	private  String  R0850_SOLD_TRAD_NET_DELTA_POS;
	private  String  R0850_TRAD_NAT_AMT;
	private  String  R0850_WITHIN_1_YEAR_NAT_AMT;
	private  String  REPORT_CODE;
	@Id
	private  String  REPORT_DATE;
	private  String  REPORT_DESC;
	private  String  REPORT_FREQUENCY;
	private  String  REPORT_VERSION;
	public String getR0820_1_TO_3_YEARS_NAT_AMT() {
		return R0820_1_TO_3_YEARS_NAT_AMT;
	}
	public void setR0820_1_TO_3_YEARS_NAT_AMT(String r0820_1_TO_3_YEARS_NAT_AMT) {
		R0820_1_TO_3_YEARS_NAT_AMT = r0820_1_TO_3_YEARS_NAT_AMT;
	}
	public String getR0820_BOUGHT_HEDG_NET_DELTA_POS() {
		return R0820_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public void setR0820_BOUGHT_HEDG_NET_DELTA_POS(String r0820_BOUGHT_HEDG_NET_DELTA_POS) {
		R0820_BOUGHT_HEDG_NET_DELTA_POS = r0820_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public String getR0820_BOUGHT_TRAD_NET_DELTA_POS() {
		return R0820_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public void setR0820_BOUGHT_TRAD_NET_DELTA_POS(String r0820_BOUGHT_TRAD_NET_DELTA_POS) {
		R0820_BOUGHT_TRAD_NET_DELTA_POS = r0820_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public String getR0820_GROSS_MKT_VAL() {
		return R0820_GROSS_MKT_VAL;
	}
	public void setR0820_GROSS_MKT_VAL(String r0820_GROSS_MKT_VAL) {
		R0820_GROSS_MKT_VAL = r0820_GROSS_MKT_VAL;
	}
	public String getR0820_HEDG_NAT_AMT() {
		return R0820_HEDG_NAT_AMT;
	}
	public void setR0820_HEDG_NAT_AMT(String r0820_HEDG_NAT_AMT) {
		R0820_HEDG_NAT_AMT = r0820_HEDG_NAT_AMT;
	}
	public String getR0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0820_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0820_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0820_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0820_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0820_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0820_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0820_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0820_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0820_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0820_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0820_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0820_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0820_NAT_AMT() {
		return R0820_NAT_AMT;
	}
	public void setR0820_NAT_AMT(String r0820_NAT_AMT) {
		R0820_NAT_AMT = r0820_NAT_AMT;
	}
	public String getR0820_NON_RES_NAT_AMT() {
		return R0820_NON_RES_NAT_AMT;
	}
	public void setR0820_NON_RES_NAT_AMT(String r0820_NON_RES_NAT_AMT) {
		R0820_NON_RES_NAT_AMT = r0820_NON_RES_NAT_AMT;
	}
	public String getR0820_OVER_3_YEARS_NAT_AMT() {
		return R0820_OVER_3_YEARS_NAT_AMT;
	}
	public void setR0820_OVER_3_YEARS_NAT_AMT(String r0820_OVER_3_YEARS_NAT_AMT) {
		R0820_OVER_3_YEARS_NAT_AMT = r0820_OVER_3_YEARS_NAT_AMT;
	}
	public String getR0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0820_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0820_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0820_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0820_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0820_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0820_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0820_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0820_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0820_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0820_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0820_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0820_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0820_PRODUCT() {
		return R0820_PRODUCT;
	}
	public void setR0820_PRODUCT(String r0820_PRODUCT) {
		R0820_PRODUCT = r0820_PRODUCT;
	}
	public String getR0820_PRO_BOUGHT_NET_GAIN_LOSS() {
		return R0820_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public void setR0820_PRO_BOUGHT_NET_GAIN_LOSS(String r0820_PRO_BOUGHT_NET_GAIN_LOSS) {
		R0820_PRO_BOUGHT_NET_GAIN_LOSS = r0820_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public String getR0820_PRO_SOLD_NET_GAIN_LOSS() {
		return R0820_PRO_SOLD_NET_GAIN_LOSS;
	}
	public void setR0820_PRO_SOLD_NET_GAIN_LOSS(String r0820_PRO_SOLD_NET_GAIN_LOSS) {
		R0820_PRO_SOLD_NET_GAIN_LOSS = r0820_PRO_SOLD_NET_GAIN_LOSS;
	}
	public String getR0820_RES_1_TO_3_YEARS_MKT_VAL() {
		return R0820_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public void setR0820_RES_1_TO_3_YEARS_MKT_VAL(String r0820_RES_1_TO_3_YEARS_MKT_VAL) {
		R0820_RES_1_TO_3_YEARS_MKT_VAL = r0820_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public String getR0820_RES_LESSTHAN_1_YEAR_MKT_VAL() {
		return R0820_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public void setR0820_RES_LESSTHAN_1_YEAR_MKT_VAL(String r0820_RES_LESSTHAN_1_YEAR_MKT_VAL) {
		R0820_RES_LESSTHAN_1_YEAR_MKT_VAL = r0820_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public String getR0820_RES_MORETHAN_3_YEARS_MKT_VAL() {
		return R0820_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public void setR0820_RES_MORETHAN_3_YEARS_MKT_VAL(String r0820_RES_MORETHAN_3_YEARS_MKT_VAL) {
		R0820_RES_MORETHAN_3_YEARS_MKT_VAL = r0820_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public String getR0820_RES_NAT_AMT() {
		return R0820_RES_NAT_AMT;
	}
	public void setR0820_RES_NAT_AMT(String r0820_RES_NAT_AMT) {
		R0820_RES_NAT_AMT = r0820_RES_NAT_AMT;
	}
	public String getR0820_SOLD_HEDG_NET_DELTA_POS() {
		return R0820_SOLD_HEDG_NET_DELTA_POS;
	}
	public void setR0820_SOLD_HEDG_NET_DELTA_POS(String r0820_SOLD_HEDG_NET_DELTA_POS) {
		R0820_SOLD_HEDG_NET_DELTA_POS = r0820_SOLD_HEDG_NET_DELTA_POS;
	}
	public String getR0820_SOLD_TRAD_NET_DELTA_POS() {
		return R0820_SOLD_TRAD_NET_DELTA_POS;
	}
	public void setR0820_SOLD_TRAD_NET_DELTA_POS(String r0820_SOLD_TRAD_NET_DELTA_POS) {
		R0820_SOLD_TRAD_NET_DELTA_POS = r0820_SOLD_TRAD_NET_DELTA_POS;
	}
	public String getR0820_TRAD_NAT_AMT() {
		return R0820_TRAD_NAT_AMT;
	}
	public void setR0820_TRAD_NAT_AMT(String r0820_TRAD_NAT_AMT) {
		R0820_TRAD_NAT_AMT = r0820_TRAD_NAT_AMT;
	}
	public String getR0820_WITHIN_1_YEAR_NAT_AMT() {
		return R0820_WITHIN_1_YEAR_NAT_AMT;
	}
	public void setR0820_WITHIN_1_YEAR_NAT_AMT(String r0820_WITHIN_1_YEAR_NAT_AMT) {
		R0820_WITHIN_1_YEAR_NAT_AMT = r0820_WITHIN_1_YEAR_NAT_AMT;
	}
	public String getR0830_1_TO_3_YEARS_NAT_AMT() {
		return R0830_1_TO_3_YEARS_NAT_AMT;
	}
	public void setR0830_1_TO_3_YEARS_NAT_AMT(String r0830_1_TO_3_YEARS_NAT_AMT) {
		R0830_1_TO_3_YEARS_NAT_AMT = r0830_1_TO_3_YEARS_NAT_AMT;
	}
	public String getR0830_BOUGHT_HEDG_NET_DELTA_POS() {
		return R0830_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public void setR0830_BOUGHT_HEDG_NET_DELTA_POS(String r0830_BOUGHT_HEDG_NET_DELTA_POS) {
		R0830_BOUGHT_HEDG_NET_DELTA_POS = r0830_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public String getR0830_BOUGHT_TRAD_NET_DELTA_POS() {
		return R0830_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public void setR0830_BOUGHT_TRAD_NET_DELTA_POS(String r0830_BOUGHT_TRAD_NET_DELTA_POS) {
		R0830_BOUGHT_TRAD_NET_DELTA_POS = r0830_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public String getR0830_GROSS_MKT_VAL() {
		return R0830_GROSS_MKT_VAL;
	}
	public void setR0830_GROSS_MKT_VAL(String r0830_GROSS_MKT_VAL) {
		R0830_GROSS_MKT_VAL = r0830_GROSS_MKT_VAL;
	}
	public String getR0830_HEDG_NAT_AMT() {
		return R0830_HEDG_NAT_AMT;
	}
	public void setR0830_HEDG_NAT_AMT(String r0830_HEDG_NAT_AMT) {
		R0830_HEDG_NAT_AMT = r0830_HEDG_NAT_AMT;
	}
	public String getR0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0830_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0830_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0830_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0830_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0830_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0830_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0830_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0830_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0830_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0830_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0830_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0830_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0830_NAT_AMT() {
		return R0830_NAT_AMT;
	}
	public void setR0830_NAT_AMT(String r0830_NAT_AMT) {
		R0830_NAT_AMT = r0830_NAT_AMT;
	}
	public String getR0830_NON_RES_NAT_AMT() {
		return R0830_NON_RES_NAT_AMT;
	}
	public void setR0830_NON_RES_NAT_AMT(String r0830_NON_RES_NAT_AMT) {
		R0830_NON_RES_NAT_AMT = r0830_NON_RES_NAT_AMT;
	}
	public String getR0830_OVER_3_YEARS_NAT_AMT() {
		return R0830_OVER_3_YEARS_NAT_AMT;
	}
	public void setR0830_OVER_3_YEARS_NAT_AMT(String r0830_OVER_3_YEARS_NAT_AMT) {
		R0830_OVER_3_YEARS_NAT_AMT = r0830_OVER_3_YEARS_NAT_AMT;
	}
	public String getR0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0830_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0830_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0830_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0830_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0830_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0830_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0830_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0830_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0830_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0830_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0830_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0830_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0830_PRODUCT() {
		return R0830_PRODUCT;
	}
	public void setR0830_PRODUCT(String r0830_PRODUCT) {
		R0830_PRODUCT = r0830_PRODUCT;
	}
	public String getR0830_PRO_BOUGHT_NET_GAIN_LOSS() {
		return R0830_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public void setR0830_PRO_BOUGHT_NET_GAIN_LOSS(String r0830_PRO_BOUGHT_NET_GAIN_LOSS) {
		R0830_PRO_BOUGHT_NET_GAIN_LOSS = r0830_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public String getR0830_PRO_SOLD_NET_GAIN_LOSS() {
		return R0830_PRO_SOLD_NET_GAIN_LOSS;
	}
	public void setR0830_PRO_SOLD_NET_GAIN_LOSS(String r0830_PRO_SOLD_NET_GAIN_LOSS) {
		R0830_PRO_SOLD_NET_GAIN_LOSS = r0830_PRO_SOLD_NET_GAIN_LOSS;
	}
	public String getR0830_RES_1_TO_3_YEARS_MKT_VAL() {
		return R0830_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public void setR0830_RES_1_TO_3_YEARS_MKT_VAL(String r0830_RES_1_TO_3_YEARS_MKT_VAL) {
		R0830_RES_1_TO_3_YEARS_MKT_VAL = r0830_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public String getR0830_RES_LESSTHAN_1_YEAR_MKT_VAL() {
		return R0830_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public void setR0830_RES_LESSTHAN_1_YEAR_MKT_VAL(String r0830_RES_LESSTHAN_1_YEAR_MKT_VAL) {
		R0830_RES_LESSTHAN_1_YEAR_MKT_VAL = r0830_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public String getR0830_RES_MORETHAN_3_YEARS_MKT_VAL() {
		return R0830_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public void setR0830_RES_MORETHAN_3_YEARS_MKT_VAL(String r0830_RES_MORETHAN_3_YEARS_MKT_VAL) {
		R0830_RES_MORETHAN_3_YEARS_MKT_VAL = r0830_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public String getR0830_RES_NAT_AMT() {
		return R0830_RES_NAT_AMT;
	}
	public void setR0830_RES_NAT_AMT(String r0830_RES_NAT_AMT) {
		R0830_RES_NAT_AMT = r0830_RES_NAT_AMT;
	}
	public String getR0830_SOLD_HEDG_NET_DELTA_POS() {
		return R0830_SOLD_HEDG_NET_DELTA_POS;
	}
	public void setR0830_SOLD_HEDG_NET_DELTA_POS(String r0830_SOLD_HEDG_NET_DELTA_POS) {
		R0830_SOLD_HEDG_NET_DELTA_POS = r0830_SOLD_HEDG_NET_DELTA_POS;
	}
	public String getR0830_SOLD_TRAD_NET_DELTA_POS() {
		return R0830_SOLD_TRAD_NET_DELTA_POS;
	}
	public void setR0830_SOLD_TRAD_NET_DELTA_POS(String r0830_SOLD_TRAD_NET_DELTA_POS) {
		R0830_SOLD_TRAD_NET_DELTA_POS = r0830_SOLD_TRAD_NET_DELTA_POS;
	}
	public String getR0830_TRAD_NAT_AMT() {
		return R0830_TRAD_NAT_AMT;
	}
	public void setR0830_TRAD_NAT_AMT(String r0830_TRAD_NAT_AMT) {
		R0830_TRAD_NAT_AMT = r0830_TRAD_NAT_AMT;
	}
	public String getR0830_WITHIN_1_YEAR_NAT_AMT() {
		return R0830_WITHIN_1_YEAR_NAT_AMT;
	}
	public void setR0830_WITHIN_1_YEAR_NAT_AMT(String r0830_WITHIN_1_YEAR_NAT_AMT) {
		R0830_WITHIN_1_YEAR_NAT_AMT = r0830_WITHIN_1_YEAR_NAT_AMT;
	}
	public String getR0840_1_TO_3_YEARS_NAT_AMT() {
		return R0840_1_TO_3_YEARS_NAT_AMT;
	}
	public void setR0840_1_TO_3_YEARS_NAT_AMT(String r0840_1_TO_3_YEARS_NAT_AMT) {
		R0840_1_TO_3_YEARS_NAT_AMT = r0840_1_TO_3_YEARS_NAT_AMT;
	}
	public String getR0840_BOUGHT_HEDG_NET_DELTA_POS() {
		return R0840_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public void setR0840_BOUGHT_HEDG_NET_DELTA_POS(String r0840_BOUGHT_HEDG_NET_DELTA_POS) {
		R0840_BOUGHT_HEDG_NET_DELTA_POS = r0840_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public String getR0840_BOUGHT_TRAD_NET_DELTA_POS() {
		return R0840_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public void setR0840_BOUGHT_TRAD_NET_DELTA_POS(String r0840_BOUGHT_TRAD_NET_DELTA_POS) {
		R0840_BOUGHT_TRAD_NET_DELTA_POS = r0840_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public String getR0840_GROSS_MKT_VAL() {
		return R0840_GROSS_MKT_VAL;
	}
	public void setR0840_GROSS_MKT_VAL(String r0840_GROSS_MKT_VAL) {
		R0840_GROSS_MKT_VAL = r0840_GROSS_MKT_VAL;
	}
	public String getR0840_HEDG_NAT_AMT() {
		return R0840_HEDG_NAT_AMT;
	}
	public void setR0840_HEDG_NAT_AMT(String r0840_HEDG_NAT_AMT) {
		R0840_HEDG_NAT_AMT = r0840_HEDG_NAT_AMT;
	}
	public String getR0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0840_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0840_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0840_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0840_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0840_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0840_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0840_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0840_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0840_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0840_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0840_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0840_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0840_NAT_AMT() {
		return R0840_NAT_AMT;
	}
	public void setR0840_NAT_AMT(String r0840_NAT_AMT) {
		R0840_NAT_AMT = r0840_NAT_AMT;
	}
	public String getR0840_NON_RES_NAT_AMT() {
		return R0840_NON_RES_NAT_AMT;
	}
	public void setR0840_NON_RES_NAT_AMT(String r0840_NON_RES_NAT_AMT) {
		R0840_NON_RES_NAT_AMT = r0840_NON_RES_NAT_AMT;
	}
	public String getR0840_OVER_3_YEARS_NAT_AMT() {
		return R0840_OVER_3_YEARS_NAT_AMT;
	}
	public void setR0840_OVER_3_YEARS_NAT_AMT(String r0840_OVER_3_YEARS_NAT_AMT) {
		R0840_OVER_3_YEARS_NAT_AMT = r0840_OVER_3_YEARS_NAT_AMT;
	}
	public String getR0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0840_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0840_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0840_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0840_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0840_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0840_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0840_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0840_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0840_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0840_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0840_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0840_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0840_PRODUCT() {
		return R0840_PRODUCT;
	}
	public void setR0840_PRODUCT(String r0840_PRODUCT) {
		R0840_PRODUCT = r0840_PRODUCT;
	}
	public String getR0840_PRO_BOUGHT_NET_GAIN_LOSS() {
		return R0840_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public void setR0840_PRO_BOUGHT_NET_GAIN_LOSS(String r0840_PRO_BOUGHT_NET_GAIN_LOSS) {
		R0840_PRO_BOUGHT_NET_GAIN_LOSS = r0840_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public String getR0840_PRO_SOLD_NET_GAIN_LOSS() {
		return R0840_PRO_SOLD_NET_GAIN_LOSS;
	}
	public void setR0840_PRO_SOLD_NET_GAIN_LOSS(String r0840_PRO_SOLD_NET_GAIN_LOSS) {
		R0840_PRO_SOLD_NET_GAIN_LOSS = r0840_PRO_SOLD_NET_GAIN_LOSS;
	}
	public String getR0840_RES_1_TO_3_YEARS_MKT_VAL() {
		return R0840_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public void setR0840_RES_1_TO_3_YEARS_MKT_VAL(String r0840_RES_1_TO_3_YEARS_MKT_VAL) {
		R0840_RES_1_TO_3_YEARS_MKT_VAL = r0840_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public String getR0840_RES_LESSTHAN_1_YEAR_MKT_VAL() {
		return R0840_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public void setR0840_RES_LESSTHAN_1_YEAR_MKT_VAL(String r0840_RES_LESSTHAN_1_YEAR_MKT_VAL) {
		R0840_RES_LESSTHAN_1_YEAR_MKT_VAL = r0840_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public String getR0840_RES_MORETHAN_3_YEARS_MKT_VAL() {
		return R0840_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public void setR0840_RES_MORETHAN_3_YEARS_MKT_VAL(String r0840_RES_MORETHAN_3_YEARS_MKT_VAL) {
		R0840_RES_MORETHAN_3_YEARS_MKT_VAL = r0840_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public String getR0840_RES_NAT_AMT() {
		return R0840_RES_NAT_AMT;
	}
	public void setR0840_RES_NAT_AMT(String r0840_RES_NAT_AMT) {
		R0840_RES_NAT_AMT = r0840_RES_NAT_AMT;
	}
	public String getR0840_SOLD_HEDG_NET_DELTA_POS() {
		return R0840_SOLD_HEDG_NET_DELTA_POS;
	}
	public void setR0840_SOLD_HEDG_NET_DELTA_POS(String r0840_SOLD_HEDG_NET_DELTA_POS) {
		R0840_SOLD_HEDG_NET_DELTA_POS = r0840_SOLD_HEDG_NET_DELTA_POS;
	}
	public String getR0840_SOLD_TRAD_NET_DELTA_POS() {
		return R0840_SOLD_TRAD_NET_DELTA_POS;
	}
	public void setR0840_SOLD_TRAD_NET_DELTA_POS(String r0840_SOLD_TRAD_NET_DELTA_POS) {
		R0840_SOLD_TRAD_NET_DELTA_POS = r0840_SOLD_TRAD_NET_DELTA_POS;
	}
	public String getR0840_TRAD_NAT_AMT() {
		return R0840_TRAD_NAT_AMT;
	}
	public void setR0840_TRAD_NAT_AMT(String r0840_TRAD_NAT_AMT) {
		R0840_TRAD_NAT_AMT = r0840_TRAD_NAT_AMT;
	}
	public String getR0840_WITHIN_1_YEAR_NAT_AMT() {
		return R0840_WITHIN_1_YEAR_NAT_AMT;
	}
	public void setR0840_WITHIN_1_YEAR_NAT_AMT(String r0840_WITHIN_1_YEAR_NAT_AMT) {
		R0840_WITHIN_1_YEAR_NAT_AMT = r0840_WITHIN_1_YEAR_NAT_AMT;
	}
	public String getR0850_1_TO_3_YEARS_NAT_AMT() {
		return R0850_1_TO_3_YEARS_NAT_AMT;
	}
	public void setR0850_1_TO_3_YEARS_NAT_AMT(String r0850_1_TO_3_YEARS_NAT_AMT) {
		R0850_1_TO_3_YEARS_NAT_AMT = r0850_1_TO_3_YEARS_NAT_AMT;
	}
	public String getR0850_BOUGHT_HEDG_NET_DELTA_POS() {
		return R0850_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public void setR0850_BOUGHT_HEDG_NET_DELTA_POS(String r0850_BOUGHT_HEDG_NET_DELTA_POS) {
		R0850_BOUGHT_HEDG_NET_DELTA_POS = r0850_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public String getR0850_BOUGHT_TRAD_NET_DELTA_POS() {
		return R0850_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public void setR0850_BOUGHT_TRAD_NET_DELTA_POS(String r0850_BOUGHT_TRAD_NET_DELTA_POS) {
		R0850_BOUGHT_TRAD_NET_DELTA_POS = r0850_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public String getR0850_GROSS_MKT_VAL() {
		return R0850_GROSS_MKT_VAL;
	}
	public void setR0850_GROSS_MKT_VAL(String r0850_GROSS_MKT_VAL) {
		R0850_GROSS_MKT_VAL = r0850_GROSS_MKT_VAL;
	}
	public String getR0850_HEDG_NAT_AMT() {
		return R0850_HEDG_NAT_AMT;
	}
	public void setR0850_HEDG_NAT_AMT(String r0850_HEDG_NAT_AMT) {
		R0850_HEDG_NAT_AMT = r0850_HEDG_NAT_AMT;
	}
	public String getR0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0850_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0850_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0850_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0850_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0850_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0850_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0850_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0850_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0850_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0850_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0850_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0850_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0850_NAT_AMT() {
		return R0850_NAT_AMT;
	}
	public void setR0850_NAT_AMT(String r0850_NAT_AMT) {
		R0850_NAT_AMT = r0850_NAT_AMT;
	}
	public String getR0850_NON_RES_NAT_AMT() {
		return R0850_NON_RES_NAT_AMT;
	}
	public void setR0850_NON_RES_NAT_AMT(String r0850_NON_RES_NAT_AMT) {
		R0850_NON_RES_NAT_AMT = r0850_NON_RES_NAT_AMT;
	}
	public String getR0850_OVER_3_YEARS_NAT_AMT() {
		return R0850_OVER_3_YEARS_NAT_AMT;
	}
	public void setR0850_OVER_3_YEARS_NAT_AMT(String r0850_OVER_3_YEARS_NAT_AMT) {
		R0850_OVER_3_YEARS_NAT_AMT = r0850_OVER_3_YEARS_NAT_AMT;
	}
	public String getR0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0850_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0850_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0850_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0850_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0850_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0850_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0850_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0850_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0850_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0850_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0850_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0850_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0850_PRODUCT() {
		return R0850_PRODUCT;
	}
	public void setR0850_PRODUCT(String r0850_PRODUCT) {
		R0850_PRODUCT = r0850_PRODUCT;
	}
	public String getR0850_PRO_BOUGHT_NET_GAIN_LOSS() {
		return R0850_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public void setR0850_PRO_BOUGHT_NET_GAIN_LOSS(String r0850_PRO_BOUGHT_NET_GAIN_LOSS) {
		R0850_PRO_BOUGHT_NET_GAIN_LOSS = r0850_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public String getR0850_PRO_SOLD_NET_GAIN_LOSS() {
		return R0850_PRO_SOLD_NET_GAIN_LOSS;
	}
	public void setR0850_PRO_SOLD_NET_GAIN_LOSS(String r0850_PRO_SOLD_NET_GAIN_LOSS) {
		R0850_PRO_SOLD_NET_GAIN_LOSS = r0850_PRO_SOLD_NET_GAIN_LOSS;
	}
	public String getR0850_RES_1_TO_3_YEARS_MKT_VAL() {
		return R0850_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public void setR0850_RES_1_TO_3_YEARS_MKT_VAL(String r0850_RES_1_TO_3_YEARS_MKT_VAL) {
		R0850_RES_1_TO_3_YEARS_MKT_VAL = r0850_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public String getR0850_RES_LESSTHAN_1_YEAR_MKT_VAL() {
		return R0850_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public void setR0850_RES_LESSTHAN_1_YEAR_MKT_VAL(String r0850_RES_LESSTHAN_1_YEAR_MKT_VAL) {
		R0850_RES_LESSTHAN_1_YEAR_MKT_VAL = r0850_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public String getR0850_RES_MORETHAN_3_YEARS_MKT_VAL() {
		return R0850_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public void setR0850_RES_MORETHAN_3_YEARS_MKT_VAL(String r0850_RES_MORETHAN_3_YEARS_MKT_VAL) {
		R0850_RES_MORETHAN_3_YEARS_MKT_VAL = r0850_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public String getR0850_RES_NAT_AMT() {
		return R0850_RES_NAT_AMT;
	}
	public void setR0850_RES_NAT_AMT(String r0850_RES_NAT_AMT) {
		R0850_RES_NAT_AMT = r0850_RES_NAT_AMT;
	}
	public String getR0850_SOLD_HEDG_NET_DELTA_POS() {
		return R0850_SOLD_HEDG_NET_DELTA_POS;
	}
	public void setR0850_SOLD_HEDG_NET_DELTA_POS(String r0850_SOLD_HEDG_NET_DELTA_POS) {
		R0850_SOLD_HEDG_NET_DELTA_POS = r0850_SOLD_HEDG_NET_DELTA_POS;
	}
	public String getR0850_SOLD_TRAD_NET_DELTA_POS() {
		return R0850_SOLD_TRAD_NET_DELTA_POS;
	}
	public void setR0850_SOLD_TRAD_NET_DELTA_POS(String r0850_SOLD_TRAD_NET_DELTA_POS) {
		R0850_SOLD_TRAD_NET_DELTA_POS = r0850_SOLD_TRAD_NET_DELTA_POS;
	}
	public String getR0850_TRAD_NAT_AMT() {
		return R0850_TRAD_NAT_AMT;
	}
	public void setR0850_TRAD_NAT_AMT(String r0850_TRAD_NAT_AMT) {
		R0850_TRAD_NAT_AMT = r0850_TRAD_NAT_AMT;
	}
	public String getR0850_WITHIN_1_YEAR_NAT_AMT() {
		return R0850_WITHIN_1_YEAR_NAT_AMT;
	}
	public void setR0850_WITHIN_1_YEAR_NAT_AMT(String r0850_WITHIN_1_YEAR_NAT_AMT) {
		R0850_WITHIN_1_YEAR_NAT_AMT = r0850_WITHIN_1_YEAR_NAT_AMT;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(String rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public String getREPORT_DESC() {
		return REPORT_DESC;
	}
	public void setREPORT_DESC(String rEPORT_DESC) {
		REPORT_DESC = rEPORT_DESC;
	}
	public String getREPORT_FREQUENCY() {
		return REPORT_FREQUENCY;
	}
	public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
		REPORT_FREQUENCY = rEPORT_FREQUENCY;
	}
	public String getREPORT_VERSION() {
		return REPORT_VERSION;
	}
	public void setREPORT_VERSION(String rEPORT_VERSION) {
		REPORT_VERSION = rEPORT_VERSION;
	}
	public CBUAE_BRF7_3_Summary_Entity4() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
