package com.bornfire.brf.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "CBUAE_BRF7_3_SUMMARYTABLE6")
public class CBUAE_BRF7_3_Summary_Entity6 {

	private  String  R0880_PRODUCT;
	private  String  R0890_1_TO_3_YEARS_NAT_AMT;
	private  String  R0890_BOUGHT_HEDG_NET_DELTA_POS;
	private  String  R0890_BOUGHT_TRAD_NET_DELTA_POS;
	private  String  R0890_GROSS_MKT_VAL;
	private  String  R0890_HEDG_NAT_AMT;
	private  String  R0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0890_NAT_AMT;
	private  String  R0890_NON_RES_NAT_AMT;
	private  String  R0890_OVER_3_YEARS_NAT_AMT;
	private  String  R0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	private  String  R0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	private  String  R0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	private  String  R0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	private  String  R0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	private  String  R0890_PRODUCT;
	private  String  R0890_PRO_BOUGHT_NET_GAIN_LOSS;
	private  String  R0890_PRO_SOLD_NET_GAIN_LOSS;
	private  String  R0890_RES_1_TO_3_YEARS_MKT_VAL;
	private  String  R0890_RES_LESSTHAN_1_YEAR_MKT_VAL;
	private  String  R0890_RES_MORETHAN_3_YEARS_MKT_VAL;
	private  String  R0890_RES_NAT_AMT;
	private  String  R0890_SOLD_HEDG_NET_DELTA_POS;
	private  String  R0890_SOLD_TRAD_NET_DELTA_POS;
	private  String  R0890_TRAD_NAT_AMT;
	private  String  R0890_WITHIN_1_YEAR_NAT_AMT;
	private  String  REPORT_CODE;
	@Id
	private  String  REPORT_DATE;
	private  String  REPORT_DESC;
	private  String  REPORT_FREQUENCY;
	private  String  REPORT_VERSION;
	public String getR0880_PRODUCT() {
		return R0880_PRODUCT;
	}
	public void setR0880_PRODUCT(String r0880_PRODUCT) {
		R0880_PRODUCT = r0880_PRODUCT;
	}
	public String getR0890_1_TO_3_YEARS_NAT_AMT() {
		return R0890_1_TO_3_YEARS_NAT_AMT;
	}
	public void setR0890_1_TO_3_YEARS_NAT_AMT(String r0890_1_TO_3_YEARS_NAT_AMT) {
		R0890_1_TO_3_YEARS_NAT_AMT = r0890_1_TO_3_YEARS_NAT_AMT;
	}
	public String getR0890_BOUGHT_HEDG_NET_DELTA_POS() {
		return R0890_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public void setR0890_BOUGHT_HEDG_NET_DELTA_POS(String r0890_BOUGHT_HEDG_NET_DELTA_POS) {
		R0890_BOUGHT_HEDG_NET_DELTA_POS = r0890_BOUGHT_HEDG_NET_DELTA_POS;
	}
	public String getR0890_BOUGHT_TRAD_NET_DELTA_POS() {
		return R0890_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public void setR0890_BOUGHT_TRAD_NET_DELTA_POS(String r0890_BOUGHT_TRAD_NET_DELTA_POS) {
		R0890_BOUGHT_TRAD_NET_DELTA_POS = r0890_BOUGHT_TRAD_NET_DELTA_POS;
	}
	public String getR0890_GROSS_MKT_VAL() {
		return R0890_GROSS_MKT_VAL;
	}
	public void setR0890_GROSS_MKT_VAL(String r0890_GROSS_MKT_VAL) {
		R0890_GROSS_MKT_VAL = r0890_GROSS_MKT_VAL;
	}
	public String getR0890_HEDG_NAT_AMT() {
		return R0890_HEDG_NAT_AMT;
	}
	public void setR0890_HEDG_NAT_AMT(String r0890_HEDG_NAT_AMT) {
		R0890_HEDG_NAT_AMT = r0890_HEDG_NAT_AMT;
	}
	public String getR0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0890_MINUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0890_MINUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0890_MINUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0890_MINUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0890_MINUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0890_MINUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0890_MINUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0890_MINUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0890_MINUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0890_MINUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0890_MINUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0890_MINUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0890_NAT_AMT() {
		return R0890_NAT_AMT;
	}
	public void setR0890_NAT_AMT(String r0890_NAT_AMT) {
		R0890_NAT_AMT = r0890_NAT_AMT;
	}
	public String getR0890_NON_RES_NAT_AMT() {
		return R0890_NON_RES_NAT_AMT;
	}
	public void setR0890_NON_RES_NAT_AMT(String r0890_NON_RES_NAT_AMT) {
		R0890_NON_RES_NAT_AMT = r0890_NON_RES_NAT_AMT;
	}
	public String getR0890_OVER_3_YEARS_NAT_AMT() {
		return R0890_OVER_3_YEARS_NAT_AMT;
	}
	public void setR0890_OVER_3_YEARS_NAT_AMT(String r0890_OVER_3_YEARS_NAT_AMT) {
		R0890_OVER_3_YEARS_NAT_AMT = r0890_OVER_3_YEARS_NAT_AMT;
	}
	public String getR0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0890_PLUSTEN_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0890_PLUSTEN_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING = r0890_PLUSTEN_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING = r0890_PLUSTEN_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING(
			String r0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING) {
		R0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING = r0890_PLUSTEN_LESSTHAN_1_YEAR_HEDG_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING() {
		return R0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public void setR0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING(
			String r0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING) {
		R0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING = r0890_PLUSTEN_LESSTHAN_1_YEAR_TRAD_NET_LOSS_GAIN_UNDERLYING;
	}
	public String getR0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT = r0890_PLUS_2BP_1_TO_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT() {
		return R0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public void setR0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT(
			String r0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT) {
		R0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT = r0890_PLUS_2BP_1_TO_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLELSHIFT;
	}
	public String getR0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT = r0890_PLUS_2BP_GREATERTHAN_3_YEARS_HEDG_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT() {
		return R0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public void setR0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT(
			String r0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT) {
		R0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT = r0890_PLUS_2BP_GREATERTHAN_3_YEARS_TRAD_NET_LOSS_GAIN_PARALLEL_SHIFT;
	}
	public String getR0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT() {
		return R0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT(
			String r0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT) {
		R0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT = r0890_PLUS_2BP_LESSTHAN_1_YEAR_HEDG_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT() {
		return R0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public void setR0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT(
			String r0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT) {
		R0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT = r0890_PLUS_2BP_LESSTHAN_1_YEAR_TRAD_NET_LOSS_PARALLELSHIFT;
	}
	public String getR0890_PRODUCT() {
		return R0890_PRODUCT;
	}
	public void setR0890_PRODUCT(String r0890_PRODUCT) {
		R0890_PRODUCT = r0890_PRODUCT;
	}
	public String getR0890_PRO_BOUGHT_NET_GAIN_LOSS() {
		return R0890_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public void setR0890_PRO_BOUGHT_NET_GAIN_LOSS(String r0890_PRO_BOUGHT_NET_GAIN_LOSS) {
		R0890_PRO_BOUGHT_NET_GAIN_LOSS = r0890_PRO_BOUGHT_NET_GAIN_LOSS;
	}
	public String getR0890_PRO_SOLD_NET_GAIN_LOSS() {
		return R0890_PRO_SOLD_NET_GAIN_LOSS;
	}
	public void setR0890_PRO_SOLD_NET_GAIN_LOSS(String r0890_PRO_SOLD_NET_GAIN_LOSS) {
		R0890_PRO_SOLD_NET_GAIN_LOSS = r0890_PRO_SOLD_NET_GAIN_LOSS;
	}
	public String getR0890_RES_1_TO_3_YEARS_MKT_VAL() {
		return R0890_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public void setR0890_RES_1_TO_3_YEARS_MKT_VAL(String r0890_RES_1_TO_3_YEARS_MKT_VAL) {
		R0890_RES_1_TO_3_YEARS_MKT_VAL = r0890_RES_1_TO_3_YEARS_MKT_VAL;
	}
	public String getR0890_RES_LESSTHAN_1_YEAR_MKT_VAL() {
		return R0890_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public void setR0890_RES_LESSTHAN_1_YEAR_MKT_VAL(String r0890_RES_LESSTHAN_1_YEAR_MKT_VAL) {
		R0890_RES_LESSTHAN_1_YEAR_MKT_VAL = r0890_RES_LESSTHAN_1_YEAR_MKT_VAL;
	}
	public String getR0890_RES_MORETHAN_3_YEARS_MKT_VAL() {
		return R0890_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public void setR0890_RES_MORETHAN_3_YEARS_MKT_VAL(String r0890_RES_MORETHAN_3_YEARS_MKT_VAL) {
		R0890_RES_MORETHAN_3_YEARS_MKT_VAL = r0890_RES_MORETHAN_3_YEARS_MKT_VAL;
	}
	public String getR0890_RES_NAT_AMT() {
		return R0890_RES_NAT_AMT;
	}
	public void setR0890_RES_NAT_AMT(String r0890_RES_NAT_AMT) {
		R0890_RES_NAT_AMT = r0890_RES_NAT_AMT;
	}
	public String getR0890_SOLD_HEDG_NET_DELTA_POS() {
		return R0890_SOLD_HEDG_NET_DELTA_POS;
	}
	public void setR0890_SOLD_HEDG_NET_DELTA_POS(String r0890_SOLD_HEDG_NET_DELTA_POS) {
		R0890_SOLD_HEDG_NET_DELTA_POS = r0890_SOLD_HEDG_NET_DELTA_POS;
	}
	public String getR0890_SOLD_TRAD_NET_DELTA_POS() {
		return R0890_SOLD_TRAD_NET_DELTA_POS;
	}
	public void setR0890_SOLD_TRAD_NET_DELTA_POS(String r0890_SOLD_TRAD_NET_DELTA_POS) {
		R0890_SOLD_TRAD_NET_DELTA_POS = r0890_SOLD_TRAD_NET_DELTA_POS;
	}
	public String getR0890_TRAD_NAT_AMT() {
		return R0890_TRAD_NAT_AMT;
	}
	public void setR0890_TRAD_NAT_AMT(String r0890_TRAD_NAT_AMT) {
		R0890_TRAD_NAT_AMT = r0890_TRAD_NAT_AMT;
	}
	public String getR0890_WITHIN_1_YEAR_NAT_AMT() {
		return R0890_WITHIN_1_YEAR_NAT_AMT;
	}
	public void setR0890_WITHIN_1_YEAR_NAT_AMT(String r0890_WITHIN_1_YEAR_NAT_AMT) {
		R0890_WITHIN_1_YEAR_NAT_AMT = r0890_WITHIN_1_YEAR_NAT_AMT;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(String rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public String getREPORT_DESC() {
		return REPORT_DESC;
	}
	public void setREPORT_DESC(String rEPORT_DESC) {
		REPORT_DESC = rEPORT_DESC;
	}
	public String getREPORT_FREQUENCY() {
		return REPORT_FREQUENCY;
	}
	public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
		REPORT_FREQUENCY = rEPORT_FREQUENCY;
	}
	public String getREPORT_VERSION() {
		return REPORT_VERSION;
	}
	public void setREPORT_VERSION(String rEPORT_VERSION) {
		REPORT_VERSION = rEPORT_VERSION;
	}
	public CBUAE_BRF7_3_Summary_Entity6() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
